---
- name: Playbook to retrieve automation platform service clusters and services, and configure service keys
  hosts: localhost
  connection: local
  vars:
    service_types: []
    services_info: []
    service_keys: []
  tasks:
    - name: GET service clusters from the API
      uri:
        url: "{{ gateway_host }}/api/gateway/v1/service_clusters/?format=json"
        method: GET
        headers:
          Content-Type: "application/json"
        user: "{{ gateway_admin_username }}"
        password: "{{ gateway_admin_password }}"
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
      register: result_clusters

    - name: GET services from the API
      uri:
        url: "{{ gateway_host }}/api/gateway/v1/services/?format=json"
        method: GET
        headers:
          Content-Type: "application/json"
        user: "{{ gateway_admin_username }}"
        password: "{{ gateway_admin_password }}"
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
      register: result_services

    - name: Collect service types
      set_fact:
        service_types: "{{ service_types + [item.service_type] }}"
      loop: "{{ result_clusters.json.results }}"

    - name: Print the list of service types
      debug:
        msg: "Service types: {{ service_types }}"

    - name: Print the number of services retrieved
      debug:
        msg: "Number of services: {{ result_services.json.count }}"

    - name: Collect service info based on service type
      set_fact:
        services_info: "{{ services_info + [{'id': item.summary_fields.service_cluster.id, 'name': item.name}] }}"
      loop: "{{ result_services.json.results }}"

    - name: Print details of each service
      debug:
        msg: "{{ item }}"
      loop: "{{ result_services.json.results }}"

    - name: Print the list of service IDs and names
      debug:
        msg: "Services Info: {{ services_info }}"

    - name: POST to the service key endpoint for each service
      uri:
        url: "{{ gateway_host }}/api/gateway/v1/service_keys/"
        method: POST
        headers:
          Content-Type: "application/json"
        user: "{{ gateway_admin_username }}"
        password: "{{ gateway_admin_password }}"
        force_basic_auth: yes
        body: "{{ {'service_cluster': item.id, 'mark_previous_inactive': true} | to_json }}"
        body_format: json
        validate_certs: no
        status_code: 201
      register: post_results
      loop: "{{ services_info }}"
      loop_control:
        index_var: loop_index

    - name: Collect service keys
      set_fact:
        service_keys: "{{ service_keys + [{'name': services_info[loop_index].name, 'key': post_results.results[loop_index].json.secret}] }}"
      loop: "{{ services_info }}"
      loop_control:
        index_var: loop_index

    - name: Print the service keys for each service
      debug:
        msg: "Service: {{ item.name }}, Key: {{ item.key }}"
      loop: "{{ service_keys }}"
