---
- name: Generate the docker-compose.yml file for gateway
  hosts: localhost
  connection: localhost
  gather_facts: False
  tasks:
    - name: Generate configs
      include_role:
        name: sources
