---
- name: Run any pre-hooks for containers
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: "{{ outer_item.key }}"
        tasks_from: initialize
      loop: "{{ enabled_containers | dict2items }}"
      when: enabled_containers[outer_item.key] | bool
      loop_control:
        loop_var: outer_item
        label: "{{ outer_item.key }}"
