---
    

- name: Plumb gateway for enabled side containers
  hosts: localhost
  gather_facts: False
  module_defaults:
    group/ansible.platform.gateway:
      gateway_hostname: "{{ gateway_host }}"
      gateway_username: "{{ gateway_admin_username }}"
      gateway_password: "{{ gateway_admin_password }}"
      gateway_validate_certs: False
  pre_tasks:
  - name: Check if API is available and returning status 200
    uri:
      url: "{{ gateway_host }}/api/"
      validate_certs: "{{ gateway_validate_certs|default(False) }}"
    register: result
    until: "result.status == 200"
    retries: 10
    delay: 5
  tasks:
    - include_role:
        name: "{{ outer_item.key }}"
        tasks_from: plumb
      loop_control:
        loop_var: outer_item
      loop: "{{ enabled_containers | dict2items }}"
      when: enabled_containers[outer_item.key] | bool
