REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'] = ('ansible_base.jwt_consumer.awx.auth.AwxJWTAuthentication',) + REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES']
ANSIBLE_BASE_JWT_KEY = 'https://aap-gw-proxy-1:9080/'
ANSIBLE_BASE_JWT_VALIDATE_CERT = False
