# Complete documentation with many more options at:
# https://docs.sonarqube.org/latest/analysis/analysis-parameters/

sonar.host.url=https://sonarcloud.io

## The unique project identifier. This is mandatory.
# Do not duplicate or reuse!
# Available characters: [a-zA-Z0-9_:\.\-]
# Must have least one non-digit.
# Recommended format: <group>:<project>
sonar.projectKey=ansible_jewel

# Customize what paths to scan. Default is .
sonar.sources=.

# Verbose name of project displayed in WUI. Default is set to the projectKey. This field is optional.
sonar.projectName=jewel

# Version of project. This field is optional.
#sonar.projectVersion=1.0

## MR settings
sonar.pullrequest.base=devel

# Tell sonar scanner where coverage files exist
sonar.python.coverage.reportPaths=service_lib/coverage.xml

sonar.issue.ignore.multicriteria=e1,e2
# Ignore https security issues in test files
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S5332
sonar.issue.ignore.multicriteria.e1.resourceKey=service_lib/tests/**/*
# Ignore string duplication issues in test files
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e2.resourceKey=service_lib/tests/**/*

# Only scan with python3
sonar.python.version=3.9,3.10,3.11

# Ignore coverage and code dupe for the tests
sonar.coverage.exclusions=service_lib/tests/**/*
sonar.cpd.exclusions=service_lib/tests/**/*
