#!/bin/bash
set -o errexit

database_ready() {
/opt/venv/bin/python <<EOF
import sys
from django.db import connection

try:
    connection.ensure_connection()
except Exception:
    sys.exit(1)
EOF
}

until database_ready
do
    echo "Waiting until the database is ready..."
    sleep 5
done

# /opt/venv/bin/python aap-gateway/manage.py migrate --noinput
# /opt/venv/bin/python aap-gateway/manage.py collectstatic --noinput

cd aap-gateway/
/usr/local/bin/supervisord -n
