#!/bin/bash
set -o errexit

GATEWAY_BASE_DIR=/opt/aap_gateway
GATEWAY_APP_DIR="${GATEWAY_BASE_DIR}/aap_gateway"
GATEWAY_PYTHON="${GATEWAY_BASE_DIR}/venv/bin/python"

database_ready() {
${GATEWAY_PYTHON} <<EOF
import sys
from django.db import connection

try:
    connection.ensure_connection()
except Exception:
    sys.exit(1)
EOF
}

until database_ready
do
    echo "Waiting until the database is ready..."
    sleep 5
done

${GATEWAY_PYTHON} ${GATEWAY_APP_DIR}/manage.py migrate --noinput
${GATEWAY_PYTHON} ${GATEWAY_APP_DIR}/manage.py collectstatic --noinput

cd ${GATEWAY_APP_DIR}
exec supervisord -n
