[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aap"
version = "0.0.1"
authors = [
  { name="Red Hat, Inc.", email="info@ansible.com" },
  { name="John Westcott IV", email="john.westcott.iv@redhat.com" },
]
description = "A Django Rest Framework authentication plugin for Ansible Automation Platform Gateway"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    #"License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'PyJWT',
  'requests',
  'django',
  'djangorestframework',
]

[project.urls]
"Homepage" = "https://github.com/ansible/aap-gateway"
"Bug Tracker" = "https://github.com/ansible/aap-gateway/issues"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py{311}-django{41,42}

[testenv]
deps = 
    django42: Django>=4.2,<4.3
    django41: Django>=4.1,<4.2
    pytest
    pytest-cov
    pytest-django
    cryptography
    pyjwt
    requests
    djangorestframework
commands = py.test --cov=src --cov-report=xml:coverage.xml
"""

[tool.pytest.ini_options]
pythonpath = [
  ".", "src"
]
addopts = [
    "--import-mode=importlib",
]
#DJANGO_SETTINGS_MODULE = "test.settings"

[tool.black]
line-length = 160
fast = true
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 160

[tool.flake8]
max-line-length = 160
extend-ignore = [ "E203" ]
