"""
Django settings for service_test_app project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from split_settings.tools import include

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i(_))sd*x)llwnn2$hqkbq2^z39649vxs-cort3p99pmmgy7f5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ansible_base.jwt_consumer',
    'ansible_base.resource_registry',
    'service_test_app',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'service_test_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'service_test_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ":memory:",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


ANSIBLE_BASE_TEAM_MODEL = 'service_test_app.Team'
ANSIBLE_BASE_ORGANIZATION_MODEL = 'service_test_app.Organization'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.keycloak.KeycloakOAuth2',
    'social_core.backends.saml.SAMLAuth',
    'social_core.backends.open_id_connect.OpenIdConnectAuth',
    'social_core.backends.keycloak.KeycloakOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)


from ansible_base.lib import dynamic_config  # noqa: E402

ANSIBLE_BASE_RESOURCE_CONFIG_MODULE = "service_test_app.resources_api"

SYSTEM_USERNAME = '_system'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'ansible_base.jwt_consumer.common.auth.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'ansible_base.rest_filters.rest_framework.type_filter_backend.TypeFilterBackend',
        'ansible_base.rest_filters.rest_framework.field_lookup_backend.FieldLookupBackend',
        'rest_framework.filters.SearchFilter',
        'ansible_base.rest_filters.rest_framework.order_backend.OrderByBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,
}

AUTH_USER_MODEL = 'service_test_app.User'
ANSIBLE_BASE_JWT_KEY = os.environ.get("ANSIBLE_BASE_JWT_KEY")

RESOURCE_SERVER = {"URL": "https://localhost", "SECRET_KEY": os.environ.get("SERVICE_TEST_APP_SECRET_KEY"), "VALIDATE_HTTPS": False}
SERVICE_BACKED_SSO_AUTH_CODE_REDIRECT_PATH = "/api/gateway/v1/legacy_auth/"

# Social auth backend settings
# We don't need settings that actually work. We just care about the server URL

# SAML
SOCIAL_AUTH_SAML_ENABLED_IDPS = {
    "KeycloakSAML": {
        "url": "https://keycloak.example.com/auth/realms/saml/protocol/saml",
        "entity_id": "https://keycloak.example.com/auth/realms/saml/protocol/saml",
        "x509cert": "cert",
        "attr_email": "email",
        "attr_groups": "groups",
        "attr_username": "username",
        "attr_last_name": "last_name",
        "attr_first_name": "first_name",
        "attr_user_permanent_id": "name_id",
    },
    "Shibboleth": {
        "url": "https://shibboleth.example.com/shib/idp",
        "entity_id": "https://shibboleth.example.com/shib/idp/",
        "x509cert": "cert",
        "attr_email": "email",
        "attr_groups": "groups",
        "attr_username": "username",
        "attr_last_name": "last_name",
        "attr_first_name": "first_name",
        "attr_user_permanent_id": "name_id",
    },
}

# OIDC
SOCIAL_AUTH_OIDC_AUTHORIZATION_URL = 'https://keycloak.example.com/auth/realms/oidc/protocol/openid-connect/auth'
SOCIAL_AUTH_OIDC_KEY = '<client_id>'
SOCIAL_AUTH_OIDC_SECRET = '<client_secret>'

# Keycloak
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL = 'https://keycloak.example.com/auth/realms/oidc/protocol/openid-connect/auth/'

ENABLE_SERVICE_BACKED_SSO = True

settings_file = os.path.join(os.path.dirname(dynamic_config.__file__), 'dynamic_settings.py')
include(settings_file)
