# Generated by Django 4.2.11 on 2024-09-04 18:35

import aap_gateway_api.managers.user
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from ._initialize_tasks import create_system_user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('managed', models.BooleanField(default=False, editable=False, help_text='Indicates if this user is managed by the system. It cannot be modified once created.')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', aap_gateway_api.managers.user.UserUnmanagedManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HTTPPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('name', models.CharField(help_text='The name of this resource', max_length=512, unique=True)),
                ('number', models.IntegerField(help_text='Port number to listen on.', unique=True, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)])),
                ('use_https', models.BooleanField(default=True, help_text='Secure this port with HTTPS.')),
                ('is_api_port', models.BooleanField(default=False, help_text='If true, this port will be used to serve the AAP service APIs. Only one port can be the API port.')),
                ('envoy_listener_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('name', models.CharField(help_text='The name of this resource', max_length=512, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='The organization description.')),
                ('managed', models.BooleanField(default=False, editable=False, help_text='Indicates if this organization is managed by the system. It cannot be modified once created.')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('member_organization', 'User is a member of this organization')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('name', models.CharField(help_text='The name of this resource', max_length=512, unique=True)),
                ('service_port', models.IntegerField(help_text='Port on the service cluster to route traffic to.', validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)])),
                ('is_service_https', models.BooleanField(help_text='Set this to true if the service cluster requires HTTPS.')),
                ('service_path', models.CharField(help_text='URL path on the AAP Service cluster to route traffic to.', max_length=255)),
                ('gateway_path', models.CharField(help_text='Path on the AAP gateway to listen to traffic on.', max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_gateway_auth', models.BooleanField(default=True, help_text='If false, the AAP gateway will not insert a gateway token into the proxied request.')),
                ('envoy_cluster_name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=50, help_text='The order to apply the routes in lower numbers are first. Items with the same value have no guaranteed order', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('node_tags', models.CharField(blank=True, default='', help_text='Comma-separated. Allows for being selective about which nodes in the service cluster receive traffic from this route. Leave blank to select all nodes.', max_length=255)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('http_port', models.ForeignKey(help_text='Port on the AAP gateway to listen to traffic on.', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='aap_gateway_api.httpport')),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('name', models.CharField(help_text='The name of this resource', max_length=512, unique=True)),
                ('service_type', models.CharField(choices=[('hub', 'hub'), ('controller', 'controller'), ('eda', 'eda'), ('gateway', 'gateway')], help_text='The type of service for this cluster.', max_length=11, unique=True)),
                ('service_id', models.UUIDField(editable=False, help_text='The unique service ID, provided by the service.', null=True, unique=True)),
                ('outlier_detection_enabled', models.BooleanField(default=True, help_text='If true, outlier detection will be used to determine if a node is unhealthy and should be ejected from the cluster.')),
                ('outlier_detection_consecutive_5xx', models.PositiveIntegerField(default=5, help_text='Number of consecutive 5xx responses to consider a node unhealthy.')),
                ('outlier_detection_interval_seconds', models.PositiveIntegerField(default=10, help_text='The time interval between ejection analysis sweeps.')),
                ('outlier_detection_base_ejection_time_seconds', models.PositiveIntegerField(default=30, help_text='The base time a node will be ejected for.')),
                ('outlier_detection_max_ejection_percent', models.PositiveIntegerField(default=33, help_text='The maximum percent of nodes that can be ejected from the cluster.')),
                ('health_checks_enabled', models.BooleanField(default=True, help_text='If true, health checks will be used to determine if a node is healthy.')),
                ('health_check_timeout_seconds', models.PositiveIntegerField(default=5, help_text='The time to wait for a health check to complete.')),
                ('health_check_interval_seconds', models.PositiveIntegerField(default=10, help_text='The time between health check requests.')),
                ('health_check_unhealthy_threshold', models.PositiveIntegerField(default=3, help_text='The number of consecutive failed health checks before a node is considered unhealthy.')),
                ('health_check_healthy_threshold', models.PositiveIntegerField(default=3, help_text='The number of consecutive successful health checks before a node is considered healthy.')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalRoute',
            fields=[
                ('route_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aap_gateway_api.route')),
            ],
            options={
                'abstract': False,
            },
            bases=('aap_gateway_api.route', models.Model),
        ),
        migrations.CreateModel(
            name='ServiceAPIRoute',
            fields=[
                ('route_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aap_gateway_api.route')),
                ('api_slug', models.SlugField(max_length=20)),
            ],
            bases=('aap_gateway_api.route', models.Model),
        ),
        migrations.CreateModel(
            name='ServiceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('name', models.CharField(help_text='The name of this resource', max_length=512, unique=True)),
                ('address', models.CharField(help_text='Network address to route traffic for this service to.', max_length=255)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated. Used to assign roles to a node, to be selective about which routes point to it.', max_length=255)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('service_cluster', models.ForeignKey(help_text='AAP Service cluster that this node belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='aap_gateway_api.servicecluster')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('name', models.CharField(help_text='The name of this resource', max_length=512, null=True, unique=True)),
                ('algorithm', models.CharField(choices=[('HS256', 'HMAC with SHA256'), ('HS384', 'HMAC with SHA384'), ('HS512', 'HMAC with SHA512')], default='HS256', max_length=10)),
                ('secret', models.TextField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('service_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_keys', to='aap_gateway_api.servicecluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='route',
            name='service_cluster',
            field=models.ForeignKey(help_text='AAP Service to route traffic to.', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='aap_gateway_api.servicecluster'),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True, verbose_name='Section Name')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('raw_value', models.TextField(blank=True, null=True, verbose_name='Raw Value')),
            ],
            options={
                'unique_together': {('section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('name', models.CharField(help_text='The name of this resource', max_length=512)),
                ('description', models.TextField(blank=True, default='', help_text='The team description.')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization of this team.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='aap_gateway_api.organization')),
                ('parents', models.ManyToManyField(blank=True, help_text='The list of teams that are parents of this team', to='aap_gateway_api.team')),
            ],
            options={
                'ordering': ('organization__name', 'name'),
                'permissions': [('member_team', 'Has all permissions granted to this team')],
                'abstract': False,
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('http_port', 'gateway_path')},
        ),
        migrations.CreateModel(
            name='MigratedUserMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('original_username', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aap_gateway_api.servicecluster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_accounts', to=settings.AUTH_USER_MODEL)),
                ('backend_classification', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('user', 'service')},
            },
        ),
        migrations.AddConstraint(
            model_name='httpport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_api_port', True)), fields=('is_api_port',), name='unique_api_port'),
        ),
        migrations.RunPython(create_system_user, migrations.RunPython.noop),
    ]
