# Generated by Django 4.2.11 on 2024-09-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from ._initialize_tasks import create_permissions_as_operation

class Migration(migrations.Migration):

    dependencies = [
        ('dab_authentication', '0013_alter_authenticator_order'),
        ('aap_gateway_api', '0001_initial'),
        ('dab_rbac', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigratedAuthenticatorMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('type', models.CharField(choices=[('legacy_password', 'Local'), ('legacy_sso', 'SSO')], max_length=32)),
                ('django_backend', models.CharField(max_length=256, null=True)),
                ('sso_server', models.CharField(max_length=512, null=True)),
                ('authenticator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='migrated_metadata', to='dab_authentication.authenticator')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aap_gateway_api.servicecluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_permissions_as_operation, migrations.RunPython.noop),
    ]
