# Generated by Django 4.2.5 on 2023-10-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_allowed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='claims',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_map_results',
        ),
    ]
