# Generated by Django 4.2.11 on 2024-10-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0002_migratedauthenticatormetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='type',
            field=models.CharField(choices=[('legacy_password', 'Local'), ('legacy_sso', 'SSO'), ('legacy_external_password', 'External Password')], max_length=32),
        ),
    ]
