# Generated by Django 4.2.5 on 2023-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0002_user_fields_to_ansible_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecluster',
            name='service_type',
            field=models.CharField(choices=[('hub', 'hub'), ('controller', 'controller'), ('eda', 'eda'), ('gateway', 'gateway')], help_text='The type of service for this cluster.', max_length=11, unique=True),
        ),
    ]
