# Generated by Django 4.2.5 on 2023-10-04 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0002_authenticator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_allowed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='claims',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='is_system_auditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_map_results',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='service_type',
            field=models.CharField(choices=[('h', 'hub'), ('c', 'controller'), ('e', 'eda'), ('g', 'gateway')], help_text='The type of service for this cluster.', max_length=1, unique=True),
        ),
        migrations.CreateModel(
            name='AuthenticatorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=None, editable=False, help_text='The date/time this resource was created')),
                ('modified_on', models.DateTimeField(default=None, editable=False, help_text='The date/time this resource was created')),
                ('revoke', models.BooleanField(default=False, help_text='If a user does not meet this rule should we revoke the permission')),
                ('map_type', models.CharField(choices=[('team', 'team'), ('is_superuser', 'is_superuser'), ('is_system_auditor', 'is_system_auditor'), ('allow', 'allow')], default='team', help_text='What does the map work on, a team, a user flag or is this an allow rule', max_length=17)),
                ('team', models.CharField(default=None, help_text='A team name this rule works on', max_length=512, null=True)),
                ('organization', models.CharField(default=None, help_text='An organization name this rule works on', max_length=512, null=True)),
                ('triggers', models.JSONField(default=dict, help_text='Trigger information for this rule')),
                ('order', models.PositiveIntegerField(default=0, help_text='The order in which this rule should be processed, smaller numbers are of higher precedence. Items with the same order will be executed in random order')),
                ('authenticator', models.ForeignKey(help_text='The authenticator this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, to='aap_gateway_api.authenticator')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='authenticatormap',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('map_type', 'team'), _negated=True), models.Q(('team__isnull', False), ('organization__isnull', False)), _connector='OR'), name='aap_gateway_api_authenticatormap_require_org_team_if_team_map'),
        ),
    ]
