# Generated by Django 4.2.5 on 2023-10-27 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0003_alter_servicecluster_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='order',
            field=models.IntegerField(default=50, help_text='The order to apply the routes in lower numbers are first. Items with the same value have no guaranteed order', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
