# Generated by Django 4.2.16 on 2024-10-22 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dab_authentication', '0014_authenticator_auto_migrate_users_to'),
        ('aap_gateway_api', '0003_alter_migratedauthenticatormetadata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpport',
            name='envoy_listener_name',
            field=models.CharField(help_text='The envoy configuration listener name for this port', max_length=255),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='authenticator',
            field=models.OneToOneField(help_text='The authenticator this user is related to', on_delete=django.db.models.deletion.CASCADE, related_name='migrated_metadata', to='dab_authentication.authenticator'),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='django_backend',
            field=models.CharField(help_text='The legacy backend type this user is associated with', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='service',
            field=models.ForeignKey(help_text='The service cluster this user came from', on_delete=django.db.models.deletion.CASCADE, to='aap_gateway_api.servicecluster'),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='sso_server',
            field=models.CharField(help_text='The URL of the SSO server, if this user is tied to an the SSO type', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='type',
            field=models.CharField(choices=[('legacy_password', 'Local'), ('legacy_sso', 'SSO'), ('legacy_external_password', 'External Password')], help_text='The type of legacy auth this user is from i.e. SSO, Local, etc', max_length=32),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='backend_classification',
            field=models.CharField(default=None, help_text='The category of authentication the user used in the service cluster', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='original_username',
            field=models.CharField(help_text='The original username used by the service cluster for this user', max_length=255),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='service',
            field=models.ForeignKey(help_text='The service cluster this user was migrated from', on_delete=django.db.models.deletion.CASCADE, to='aap_gateway_api.servicecluster'),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='user',
            field=models.ForeignKey(help_text='The gateway user this migrated user is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='original_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.CharField(blank=True, help_text='A description of this route.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='envoy_cluster_name',
            field=models.CharField(help_text='The name of the envoy cluster this route belongs to', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceapiroute',
            name='api_slug',
            field=models.SlugField(help_text='An internally generated API slug for this Service API Route', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='algorithm',
            field=models.CharField(choices=[('HS256', 'HMAC with SHA256'), ('HS384', 'HMAC with SHA384'), ('HS512', 'HMAC with SHA512')], default='HS256', help_text='The algorithm used to generate the service key', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this service key active'),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='secret',
            field=models.TextField(editable=False, help_text='The secret, will only be plain text on generation, afterwards it will be encrypted'),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='service_cluster',
            field=models.ForeignKey(help_text='The service cluster this key is for', on_delete=django.db.models.deletion.CASCADE, related_name='service_keys', to='aap_gateway_api.servicecluster'),
        ),
    ]
