# Generated by Django 4.2.5 on 2023-11-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0004_route_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512),
        ),
    ]
