# Generated by Django 4.2.16 on 2024-11-21 11:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dab_authentication', '0015_alter_authenticator_category_and_more'),
        ('aap_gateway_api', '0004_alter_httpport_envoy_listener_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='httpport',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='httpport',
            name='envoy_listener_name',
            field=models.CharField(help_text='The envoy configuration listener name for this port.', max_length=255),
        ),
        migrations.AlterField(
            model_name='httpport',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='httpport',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='httpport',
            name='name',
            field=models.CharField(help_text='The name of this resource.', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='httpport',
            name='number',
            field=models.IntegerField(help_text='The port number to listen on.', unique=True, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='authenticator',
            field=models.OneToOneField(help_text='The authenticator this user is related to.', on_delete=django.db.models.deletion.CASCADE, related_name='migrated_metadata', to='dab_authentication.authenticator'),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='django_backend',
            field=models.CharField(help_text='The legacy backend type this user is associated with.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='service',
            field=models.ForeignKey(help_text='The service cluster this user came from.', on_delete=django.db.models.deletion.CASCADE, to='aap_gateway_api.servicecluster'),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='sso_server',
            field=models.CharField(help_text='The URL of the SSO server, if this user is tied to an the SSO type.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='migratedauthenticatormetadata',
            name='type',
            field=models.CharField(choices=[('legacy_password', 'Local'), ('legacy_sso', 'SSO'), ('legacy_external_password', 'External Password')], help_text='The type of legacy auth this user is from i.e. SSO, Local, etc.', max_length=32),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='backend_classification',
            field=models.CharField(default=None, help_text='The category of authentication the user used in the service cluster.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='original_username',
            field=models.CharField(help_text='The original username used by the service cluster for this user.', max_length=255),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='service',
            field=models.ForeignKey(help_text='The service cluster this user was migrated from.', on_delete=django.db.models.deletion.CASCADE, to='aap_gateway_api.servicecluster'),
        ),
        migrations.AlterField(
            model_name='migratedusermetadata',
            name='user',
            field=models.ForeignKey(help_text='The gateway user this migrated user is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='original_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='The name of this resource.', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='envoy_cluster_name',
            field=models.CharField(help_text='The name of the envoy cluster this route belongs to.', max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='gateway_path',
            field=models.CharField(help_text='The path on the AAP gateway to listen to traffic on.', max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='http_port',
            field=models.ForeignKey(help_text='The port on the AAP gateway to listen to traffic on.', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='aap_gateway_api.httpport'),
        ),
        migrations.AlterField(
            model_name='route',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='route',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(help_text='The name of this resource.', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='node_tags',
            field=models.CharField(blank=True, default='', help_text='A comma-separated list of nodes in the service cluster to receive traffic from this route.  Leave blank to select all nodes.', max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='order',
            field=models.IntegerField(default=50, help_text='The order to apply the routes in; lower numbers are first. Items with the same value have no guaranteed order', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='service_cluster',
            field=models.ForeignKey(help_text='The AAP Service to route traffic to.', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='aap_gateway_api.servicecluster'),
        ),
        migrations.AlterField(
            model_name='route',
            name='service_path',
            field=models.CharField(help_text='The URL path on the AAP Service cluster to route traffic to.', max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='service_port',
            field=models.IntegerField(help_text='The port on the service cluster to route traffic to.', validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='serviceapiroute',
            name='api_slug',
            field=models.SlugField(help_text='An internally generated API slug for this Service API Route.', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='name',
            field=models.CharField(help_text='The name of this resource.', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='outlier_detection_consecutive_5xx',
            field=models.PositiveIntegerField(default=5, help_text='The number of consecutive 5xx responses to consider a node unhealthy.'),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='service_id',
            field=models.UUIDField(editable=False, help_text='The unique service ID provided by the service.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='algorithm',
            field=models.CharField(choices=[('HS256', 'HMAC with SHA256'), ('HS384', 'HMAC with SHA384'), ('HS512', 'HMAC with SHA512')], default='HS256', help_text='The algorithm used to generate the service key.', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this service key active.'),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='name',
            field=models.CharField(help_text='The name of this resource.', max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='secret',
            field=models.TextField(editable=False, help_text='The secret will only be plain text on generation, afterwards it will be encrypted.'),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='address',
            field=models.CharField(help_text='The network address to route traffic for this service to.', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='name',
            field=models.CharField(help_text='The name of this resource.', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='service_cluster',
            field=models.ForeignKey(help_text='The AAP Service cluster that this node belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='aap_gateway_api.servicecluster'),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='A comma-separated list of roles to assign to a node; to be selective about which routes point to it.', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='The name of this resource.', max_length=512),
        ),
        migrations.AlterField(
            model_name='team',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='The list of teams that are parents of this team.', to='aap_gateway_api.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
    ]
