# Generated by Django 4.2.7 on 2024-01-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0005_alter_environment_name_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='environment',
            field=models.ForeignKey(help_text='The environment this organization belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='aap_gateway_api.environment'),
        ),
    ]
