# Generated by Django 4.2.16 on 2024-12-04 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from ._initialize_tasks import create_default_service_types, migrate_service_types


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0005_alter_httpport_created_alter_httpport_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.')),
                ('name', models.CharField(help_text='The name of this resource.', max_length=512, unique=True)),
                ('ping_url', models.CharField(help_text='URL to the ping/status page of the service, ex. /pulp/api/v3/status/', max_length=255)),
                ('login_path', models.CharField(help_text='API path to login for service, ex. /v1/auth/session/login/', max_length=255, null=True)),
                ('logout_path', models.CharField(help_text='API path to logout for service, ex. /logout/', max_length=255, null=True)),
                ('service_index_path', models.CharField(help_text='API path to resource service index endpoint, ex. /v2/service-index/', max_length=255, null=True)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='servicecluster',
            old_name='service_type',
            new_name='service_type_name',
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='service_type',
            field=models.ForeignKey(help_text='The AAP service type of this service cluster.', on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='aap_gateway_api.servicetype', null=True),
        ),
        migrations.RunPython(create_default_service_types, migrations.RunPython.noop),
        migrations.RunPython(migrate_service_types, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='servicecluster',
            name='service_type_name'
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='service_type',
            field=models.ForeignKey(help_text='The AAP service type of this service cluster.', on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='aap_gateway_api.servicetype', null=False),
        ),
    ]
