# Generated by Django 4.2.17 on 2025-04-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0005_alter_httpport_created_alter_httpport_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecluster',
            name='service_type',
            field=models.CharField(choices=[('hub', 'hub'), ('controller', 'controller'), ('eda', 'eda'), ('gateway', 'gateway'), ('lightspeed', 'lightspeed')], help_text='The type of service for this cluster.', max_length=11, unique=True),
        ),
    ]
