# Generated by Django 4.2.17 on 2024-12-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0006_servicetype_alter_servicecluster_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='ping_url',
            field=models.CharField(help_text='URL to the ping/status page of the service, ex. /pulp/api/v3/status/', max_length=255, null=True),
        ),
    ]
