# Generated by Django 4.2.7 on 2024-01-23 15:55

from django.db import migrations, models
from django.db.models import F, ExpressionWrapper
from uuid import uuid4

HELP_TEXT = 'The name of this resource'


def set_http_port_name(apps, schema_editor):
    """ Set name = envoy_listener_name """
    db_alias = schema_editor.connection.alias
    HttpPort = apps.get_model("aap_gateway_api", "HttpPort")  # NOSONAR
    HttpPort.objects.using(db_alias).update(name=F("envoy_listener_name"))


def set_service_cluster_name(apps, schema_editor):
    """ Set name = service_type """
    db_alias = schema_editor.connection.alias
    ServiceCluster = apps.get_model("aap_gateway_api", "ServiceCluster")  # NOSONAR
    ServiceCluster.objects.using(db_alias).update(name=F("service_type"))


def set_service_node_name(apps, schema_editor):
    """ Set name = 'Service Node {address} ({service_cluster.service_type})' """
    db_alias = schema_editor.connection.alias
    ServiceNode = apps.get_model("aap_gateway_api", "ServiceNode")  # NOSONAR
    for service_node in ServiceNode.objects.select_related("service").using(db_alias).all():
        service_node.name = f"Service Node {service_node.address} ({service_node.service.service_type})"
        service_node.save()


def set_route_name(apps, schema_editor):
    """ Set name:
        - ServiceApiRoute: 'API {api_slug} ({port.number})
        - AdditionalRoute: 'Route {gateway_path} ({port.number})
    """
    db_alias = schema_editor.connection.alias
    ServiceApiRoute = apps.get_model("aap_gateway_api", "ServiceApiRoute")  # NOSONAR
    for api_route in ServiceApiRoute.objects.using(db_alias).select_related("port").filter(name__isnull=True).all():
        api_route.name = f"API {api_route.api_slug} ({api_route.port.number})"
        api_route.save()

    AdditionalRoute = apps.get_model("aap_gateway_api", "AdditionalRoute")  # NOSONAR
    for add_route in AdditionalRoute.objects.using(db_alias).select_related("port").filter(name__isnull=True).all():
        add_route.name = f"Route {add_route.gateway_path} ({add_route.port.number})"
        add_route.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0006_alter_organization_environment'),
    ]

    operations = [

        # --- Http Port ---
        migrations.AddField(
            model_name='httpport',
            name='name',
            field=models.CharField(default=str(uuid4()), help_text=HELP_TEXT, max_length=512),
            preserve_default=False
        ),
        migrations.RunPython(set_http_port_name, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='httpport',
            name='name',
            field=models.CharField(help_text=HELP_TEXT, max_length=512, unique=True)
        ),

        # --- Service Cluster ---
        migrations.AddField(
            model_name='servicecluster',
            name='name',
            field=models.CharField(default=str(uuid4()), help_text=HELP_TEXT, max_length=512),
            preserve_default=False
        ),
        migrations.RunPython(set_service_cluster_name, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicecluster',
            name='name',
            field=models.CharField(help_text=HELP_TEXT, max_length=512, unique=True),
        ),

        # --- Service Node ---
        migrations.AlterUniqueTogether(
            name='servicenode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicenode',
            name='name',
            field=models.CharField(default=str(uuid4()), help_text=HELP_TEXT, max_length=512),
            preserve_default=False
        ),
        migrations.RunPython(set_service_node_name, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicenode',
            name='name',
            field=models.CharField(help_text=HELP_TEXT, max_length=512, unique=True),
        ),

        # --- ServiceApiRoute / AdditionalRoute ---
        # It already has name, but not unique (migration 0005)
        migrations.RunPython(set_route_name, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(help_text=HELP_TEXT, max_length=512, unique=True),
        ),
    ]
