# Generated by Django 4.2.17 on 2025-01-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0007_alter_servicetype_ping_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_internal_route',
            field=models.BooleanField(default=False, help_text='If true, the AAP gateway will only allow other AAP services to access this route. Requires gateway auth to be enabled.'),
        ),
    ]
