# Generated by Django 4.2.7 on 2024-01-26 14:25

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models
import django.db.models.deletion


def create_system_user(apps, schema_editor):
    """
    Create the system user using the username in settings.

    The user is self-referential in its created_by and modified_by fields.
    It is inactive, only used for attributing internal changes to the system.
    """
    User = get_user_model()
    system_username = settings.SYSTEM_USERNAME
    if not User.objects.filter(username=system_username).exists():
        # Avoid using .create_user() here because it'll call save and we can't
        # pass in our warn_nonexistent_system_user arg.
        system_user = User(username=system_username, is_active=False)
        system_user.save(warn_nonexistent_system_user=False)
        system_user.created_by = system_user
        system_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0007_alter_servicenode_unique_together_httpport_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The organization description.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The list of users in this organization.', related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The team description.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(help_text='The organization of this team.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='aap_gateway_api.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=None, editable=False, help_text='The date/time this resource was created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_on',
            field=models.DateTimeField(default=None, editable=False, help_text='The date/time this resource was created'),
        ),
        migrations.RunPython(create_system_user),
    ]
