# Generated by Django 4.2.17 on 2025-01-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0008_route_is_internal_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecluster',
            name='auth_type',
            field=models.CharField(choices=[('JWT', 'JWT'), ('BASIC', 'Basic auth'), ('TOKEN', 'Bearer token')], default='JWT', help_text='The authorization type for this service.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='dns_discovery_type',
            field=models.CharField(choices=[('LOGICAL_DNS', 'Logical DNS'), ('STRICT_DNS', 'Strict DNS')], default='STRICT_DNS', help_text='The DNS service discovery type for this service.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='dns_lookup_family',
            field=models.CharField(choices=[('V4_ONLY', 'IPv4 only'), ('V6_ONLY', 'IPv6 only'), ('AUTO', 'Auto (IPv6 preferred)'), ('ALL', 'All IPv4 and IPv6 addresses'), ('V4_PREFERRED', 'IPv4 preferred')], default='ALL', help_text='DNS lookup type for this service.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='upstream_hostname',
            field=models.CharField(blank=True, default='', help_text='Set this value to enable server name identification on associated routes.', max_length=255),
        ),
    ]
