# Generated by Django 4.2.7 on 2024-02-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0009_alter_team_options_organization_admins_team_admins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='port',
            new_name='http_port',
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('http_port', 'gateway_path')},
        ),
    ]
