# Generated by Django 4.2.17 on 2025-04-09 17:59

import django.core.validators
from django.db import migrations, models

from ._initialize_tasks import (
    update_service_ping_url,
    change_outlier_detection_max_ejection_percent_from_33_to_100,
    change_outlier_detection_max_ejection_percent_from_100_to_33
)


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0009_servicecluster_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecluster',
            name='healthy_panic_threshold',
            field=models.PositiveIntegerField(default=0, help_text='The percentage of failed hosts when the proxy will panic and start routing traffic to all nodes. Set to 0 to disable this.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='outlier_detection_max_ejection_percent',
            field=models.PositiveIntegerField(default=100, help_text='The maximum percent of nodes that can be ejected from the cluster.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(update_service_ping_url, migrations.RunPython.noop),
        migrations.RunPython(change_outlier_detection_max_ejection_percent_from_33_to_100, change_outlier_detection_max_ejection_percent_from_100_to_33),
    ]
