# Generated by Django 4.2.7 on 2024-02-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0010_rename_port_route_http_port_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicenode',
            old_name='service',
            new_name='service_cluster',
        ),
    ]
