# Generated by Django 4.2.23 on 2025-06-19 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0010_servicecluster_healthy_panic_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIPluginRoute',
            fields=[
                ('route_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aap_gateway_api.route')),
                ('ui_plugin_path', models.CharField(help_text='The relative path to the UI plugin on the service cluster.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('aap_gateway_api.route', models.Model),
        ),
    ]
