# Generated by Django 4.2.7 on 2024-03-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0011_rename_service_servicenode_service_cluster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='environment',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
    ]
