# Generated by Django 4.2.21 on 2025-07-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0011_uipluginroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MigratedAuthenticatorMetadata',
        ),
    ]
