# Generated by Django 4.2.7 on 2024-03-11 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0012_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='httpport',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='httpport',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='servicecluster',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='servicecluster',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='servicenode',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='servicenode',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='httpport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='httpport',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicecluster',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicenode',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
    ]
