# Generated by Django 4.2.21 on 2025-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0012_delete_migratedauthenticatormetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_controller_password',
            field=models.BooleanField(blank=True, default=False, editable=False, help_text="Indicates if this user's password is managed by Controller. It cannot be modified once created."),
        ),
    ]
