# Generated by Django 4.2.7 on 2024-03-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0013_remove_environment_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecluster',
            name='service_id',
            field=models.UUIDField(help_text='The unique service ID, provided by the service.', null=True, unique=True),
        ),
    ]
