# Generated by Django 4.2.21 on 2025-07-21 12:44

from django.db import migrations, models
import django.db.models.deletion

def populate_last_login_from(apps, schema_editor):
    User = apps.get_model('aap_gateway_api', 'User')
    AuthenticatorUser = apps.get_model('dab_authentication', 'AuthenticatorUser')
    for user in User.objects.filter(last_login__isnull=False):
        # Order by the AuthenticatorUser's modified date descending to get the most recently used authenticator
        # During migration, we use the most recently modified authenticator relationship as a reasonable default
        auth_user = AuthenticatorUser.objects.filter(user=user).order_by('-modified').first()
        if auth_user and auth_user.provider:
            user.last_login_from = auth_user.provider
            user.save(update_fields=["last_login_from"])


class Migration(migrations.Migration):

    dependencies = [
        ("aap_gateway_api", "0013_user_use_controller_password"),
        ("dab_authentication", "0018_authenticatoruser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_from",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The authenticator the user last logged in with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dab_authentication.authenticator",
            ),
        ),
        migrations.RunPython(populate_last_login_from, migrations.RunPython.noop),
    ]
