# Generated by Django 4.2.11 on 2024-04-12 14:59

from django.db import migrations
from django.apps import apps as global_apps

from ansible_base.rbac.management import create_dab_permissions

def create_permissions_as_operation(apps, schema_editor):
    create_dab_permissions(global_apps.get_app_config("aap_gateway_api"), apps=apps)


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0015_alter_httpport_created_by_alter_httpport_modified_by_and_more'),
        ('dab_rbac', '__first__'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('organization__name', 'name'), 'permissions': [('member_team', 'Has all permissions granted to this team')]},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('member_organization', 'User is a member of this organization')]},
        ),
        migrations.RunPython(create_permissions_as_operation, migrations.RunPython.noop),
        # NOTE: managed roles used to be created here but were moved to post_migrate data creation
        # we still need DAB RBAC permissions created sometime in the initial migrations
    ]
