# Generated by Django 4.2.11 on 2024-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0016_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='managed',
            field=models.BooleanField(default=False, editable=False, help_text='Indicates if this organization is managed by the system. It cannot be modified once created.'),
        ),
    ]
