# Generated by Django 4.2.11 on 2024-04-30 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0017_organization_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('algorithm', models.CharField(choices=[('HS256', 'HMAC with SHA256'), ('HS384', 'HMAC with SHA384'), ('HS512', 'HMAC with SHA512')], default='HS256', max_length=10)),
                ('secret', models.TextField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('service_cluster', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='service_keys', to='aap_gateway_api.servicecluster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
