# Generated by Django 4.2.11 on 2024-05-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0018_servicekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_system_auditor',
        ),
    ]
