# Generated by Django 4.2.6 on 2024-05-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0019_remove_user_is_system_auditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicekey',
            name='service_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_keys', to='aap_gateway_api.servicecluster'),
        ),
    ]
