# Generated by Django 4.2.11 on 2024-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0020_alter_servicekey_service_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed',
            field=models.BooleanField(default=False, editable=False, help_text='Indicates if this user is managed by the system. It cannot be modified once created.'),
        ),
    ]
