# Generated with AI assistance: Claude Code (Anthropic)

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aap_gateway_api", "0017_add_fallback_authentication_to_local_authenticators"),
        ("sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="UserSessionMembership",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created", models.DateTimeField(default=django.utils.timezone.now, help_text="When this session was first tracked.")),
                        (
                            "session",
                            models.OneToOneField(
                                help_text="The Django session associated with this membership.",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="membership",
                                to="sessions.session",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                help_text="The user who owns this session.",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="session_memberships",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "app_label": "aap_gateway_api",
                    },
                ),
            ],
            database_operations=[
                # Use conditional SQL so the migration is idempotent.
                # This handles the snapshot-import scenario where
                # artifact_import overwrites django_migrations (removing
                # the record for this migration) without dropping the
                # physical table created by a previous install.
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'aap_gateway_api_usersessionmembership'
                        ) THEN
                            CREATE TABLE "aap_gateway_api_usersessionmembership" (
                                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                "created" timestamp with time zone NOT NULL,
                                "session_id" varchar(40) NOT NULL UNIQUE,
                                "user_id" bigint NOT NULL
                            );
                            ALTER TABLE "aap_gateway_api_usersessionmembership"
                                ADD CONSTRAINT "aap_gateway_api_user_session_id_6c14833a_fk_django_se"
                                FOREIGN KEY ("session_id")
                                REFERENCES "django_session" ("session_key")
                                DEFERRABLE INITIALLY DEFERRED;
                            ALTER TABLE "aap_gateway_api_usersessionmembership"
                                ADD CONSTRAINT "aap_gateway_api_user_user_id_c64c4000_fk_aap_gatew"
                                FOREIGN KEY ("user_id")
                                REFERENCES "aap_gateway_api_user" ("id")
                                DEFERRABLE INITIALLY DEFERRED;
                            CREATE INDEX "aap_gateway_api_usersessionmembership_session_id_6c14833a_like"
                                ON "aap_gateway_api_usersessionmembership" ("session_id" varchar_pattern_ops);
                            CREATE INDEX "aap_gateway_api_usersessionmembership_user_id_c64c4000"
                                ON "aap_gateway_api_usersessionmembership" ("user_id");
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "aap_gateway_api_usersessionmembership";',
                ),
            ],
        ),
    ]
