# Generated by Django 4.2.11 on 2024-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0021_user_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicekey',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512, null=True, unique=True),
        ),
    ]
