# Generated by Django 4.2.6 on 2024-05-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0022_servicekey_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.RemoveField(
            model_name='team',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
    ]
