# Generated by Django 5.2.9 on 2026-06-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aap_gateway_api", "0023_remove_console_service_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrateServiceDataLastRolePK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_slug",
                    models.CharField(
                        help_text="API slug of the upstream service (e.g. controller, hub, eda)",
                        max_length=255,
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[("user", "User"), ("team", "Team")],
                        help_text="Whether this cursor tracks user or team role assignments",
                        max_length=4,
                    ),
                ),
                (
                    "last_pk",
                    models.BigIntegerField(
                        default=0,
                        help_text="PK of the last successfully processed role assignment from this service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Migrate Service Data Role Assignment Cursor",
                "verbose_name_plural": "Migrate Service Data Role Assignment Cursors",
                "unique_together": {("service_slug", "assignment_type")},
            },
        ),
    ]
