# Generated by Django 5.2.9 on 2026-06-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0023_remove_console_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_container_registry',
            field=models.BooleanField(
                default=False,
                help_text='If true, this route serves a container registry endpoint and the gateway will enforce Basic credential validation during the auth flow.',
            ),
        ),
    ]
