# Generated by Django 4.2.11 on 2024-07-17 11:51

import aap_gateway_api.managers.user
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0023_remove_users_and_admins'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', aap_gateway_api.managers.user.UserUnmanagedManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
