# Generated by Django 4.2.11 on 2024-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0024_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecluster',
            name='health_check_healthy_threshold',
            field=models.PositiveIntegerField(default=3, help_text='The number of consecutive successful health checks before a node is considered healthy.'),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='health_check_interval_seconds',
            field=models.PositiveIntegerField(default=10, help_text='The time between health check requests.'),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='health_check_timeout_seconds',
            field=models.PositiveIntegerField(default=5, help_text='The time to wait for a health check to complete.'),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='health_check_unhealthy_threshold',
            field=models.PositiveIntegerField(default=3, help_text='The number of consecutive failed health checks before a node is considered unhealthy.'),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='health_checks_enabled',
            field=models.BooleanField(default=True, help_text='If true, health checks will be used to determine if a node is healthy.'),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='outlier_detection_base_ejection_time_seconds',
            field=models.PositiveIntegerField(default=30, help_text='The base time a node will be ejected for.'),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='outlier_detection_consecutive_5xx',
            field=models.PositiveIntegerField(default=5, help_text='Number of consecutive 5xx responses to consider a node unhealthy.'),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='outlier_detection_enabled',
            field=models.BooleanField(default=True, help_text='If true, outlier detection will be used to determine if a node is unhealthy and should be ejected from the cluster.'),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='outlier_detection_interval_seconds',
            field=models.PositiveIntegerField(default=10, help_text='The time interval between ejection analysis sweeps.'),
        ),
        migrations.AddField(
            model_name='servicecluster',
            name='outlier_detection_max_ejection_percent',
            field=models.PositiveIntegerField(default=33, help_text='The maximum percent of nodes that can be ejected from the cluster.'),
        ),
    ]
