# Generated by Django 4.2.11 on 2024-08-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0025_servicecluster_health_check_healthy_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='node_tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated. Allows for being selective about which nodes receive traffic from this route.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicenode',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated. Used to assign roles to a node, to be selective about which routes point to it.', max_length=255),
        ),
    ]
