# Generated by Django 5.2.9 on 2026-09-10 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aap_gateway_api', '0026_servicecluster_outlier_detection_local_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicekey',
            name='algorithm',
            field=models.CharField(
                choices=[('HS256', 'HMAC with SHA256'), ('HS384', 'HMAC with SHA384'), ('HS512', 'HMAC with SHA512')],
                default='HS256',
                editable=False,
                help_text='The algorithm used to generate the service key.',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='service_cluster',
            field=models.ForeignKey(
                editable=False,
                help_text='The service cluster this key is for',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='service_keys',
                to='aap_gateway_api.servicecluster',
            ),
        ),
    ]
