# Generated by Django 4.2.11 on 2024-08-10 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0026_route_node_tags_servicenode_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigratedUserMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created')),
                ('original_username', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aap_gateway_api.servicecluster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'service')},
            },
        ),
        migrations.CreateModel(
            name='SocialMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=256)),
                ('backend_type', models.CharField(max_length=256)),
                ('sso_server', models.CharField(max_length=256, null=True)),
                ('migrated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_backends', to='aap_gateway_api.migratedusermetadata')),
            ],
        ),
    ]
