# Generated by Django 4.2.11 on 2024-08-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0027_migratedusermetadata_socialmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='node_tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated. Allows for being selective about which nodes in the service cluster receive traffic from this route. Leave blank to select all nodes.', max_length=255),
        ),
    ]
