# Generated by Django 4.2.14 on 2024-09-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0029_migratedauthenticatormetadata_delete_socialmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='migratedusermetadata',
            name='backend_classification',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
