---
- name: Create RADIUS config directory
  file:
    path: "{{ radius_config_dir }}"
    state: directory

- name: Copy config files
  template:
    src: "{{ radius_file }}.j2"
    dest: "{{ radius_config_dir }}/{{ radius_file }}"
  loop_control:
    loop_var: radius_file
  loop:
    - "clients.conf"
    - "authorize"
