---
- name: RADIUS authenticator
  ansible.gateway_configuration.authenticator:
    name: "{{ radius_authenticator_name }}"
    slug: "{{ radius_authenticator_name | replace(' ', '') | lower }}"
    enabled: True
    create_objects: True
    remove_users: True
    configuration: "{{ radius_configuration }}"
    type: "ansible_base.authentication.authenticator_plugins.radius"    

- name: RADIUS authenticator org map
  ansible.gateway_configuration.authenticator_map:
    name: "{{ radius_auth_map_name }} - org"
    authenticator: "{{ radius_authenticator_name }}"
    map_type: "organization"
    role: "Organization Member"
    organization: "Default"
    order: 0
    triggers:
      always: {}
