---
private_key_file: ../generated/keycloak.key
public_key_file: ../generated/keycloak.cert
public_key_cert: ../generated/keycloak.pub
keycloak_realm_template: ../generated/keycloak.gateway.realm.json
oidc_adapter_name: "Dev Keycloak Container"
url_base: "https://{{ (oidc_reference == '') | ternary(oidc_reference, container_reference) }}:{{ keycloak_exposed_port }}"
init_file: "{{ sources_dest }}/keycloak_initialized"
