---
ldap_cert_dir: '{{ sources_dest }}/ldap_certs'
ldap_diff_dir: '{{ sources_dest }}/ldap_diffs'
ldap_public_key_file: '{{ ldap_cert_dir }}/{{ ldap_public_key_file_name }}'
ldap_private_key_file: '{{ ldap_cert_dir }}/{{ ldap_private_key_file_name }}'
ldap_cert_subject: "/C=US/ST=NC/L=Durham/O=gateway/CN=devenv"
ldap_container_name: "Dev LDAP Container"
ldap_auth_map_name: "Dev LDAP Container Map"

ldap_group_mappings:
  - {ldap_group: 'admins', map_type: 'is_superuser', trigger_type: 'has_or'}
  - {ldap_group: 'auditors', map_type: 'role', role: 'Platform Auditor', trigger_type: 'has_or'}
  - {ldap_group: 'users', map_type: 'allow', trigger_type: 'has_and'}

ldap_configuration:
  SERVER_URI:
    - "ldap://ldap:1389"
  BIND_DN: "cn={{ ldap_admin_username }},dc=example,dc=org"
  BIND_PASSWORD: "{{ ldap_admin_password }}"
  START_TLS: false
  CONNECTION_OPTIONS:
    OPT_REFERRALS: 0
    OPT_NETWORK_TIMEOUT: 30
  USER_SEARCH:
    - "ou=users,dc=example,dc=org"
    - "SCOPE_SUBTREE"
    - "(cn=%(user)s)"
  USER_DN_TEMPLATE: "cn=%(user)s,ou=users,dc=example,dc=org"
  USER_ATTR_MAP:
    email: "mail"
    last_name: "sn"
    first_name: "givenName"
  GROUP_SEARCH:
    - "ou=groups,dc=example,dc=org"
    - "SCOPE_SUBTREE"
    - "(objectClass=groupOfNames)"
  GROUP_TYPE: "MemberDNGroupType"
  GROUP_TYPE_PARAMS:
    name_attr: "cn"
    member_attr: "member"

ldap_users:
  - username: 'ldap_admin'
    password: 'admin123'
    title:
      - "Engineering"
      - "Database Team"
      - "Research Division"
      - "Platform Administrators"
      - "East Coast Region"
      - "<script>alert('hey')</script>East Coast Region<script>alert('ho')</script>"
  - username: 'ldap_auditor'
    password: 'audit123'
    title:
      - "Engineering"
      - "Database Team"
      - "Security Auditors"
      - "Compliance Team"
      - "West Coast Region"
  - username: 'ldap_unpriv'
    password: 'unpriv123'
  - username: 'ldap_org_admin'
    password: 'orgadmin123'
    title:
      - "Engineering"
      - "Organization Administrators"
      - "Management Team"
      - "Central Region"

ldap_groups:
  - name: org_admins
    members:
      - ldap_org_admin
  - name: users
    members:
      - ldap_admin
      - ldap_auditor
      - ldap_unpriv
      - ldap_org_admin
  - name: admins
    members:
      - ldap_admin
  - name: auditors
    members:
      - ldap_auditor
