- name: Render docker templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ sources_dest }}/{{ item }}"
    mode: '0600'
  loop:
    - docker-compose.yml
    - Dockerfile

- name: Create Redis cert directory
  file:
    path: "{{ redis_generated_dir }}"
    state: directory

- name: Generate Redis certs
  command: '{{ item.command }}'
  args:
    creates: "{{ item.creates }}"
  loop:
    - command: 'openssl ecparam -out {{ redis_ca_root_key_file }} -name prime256v1 -genkey'
      creates: "{{ redis_ca_root_key_file }}"
      title: Generate Redis CA Key
    - command: 'openssl req -new -sha256 -key {{ redis_ca_root_key_file }} -out {{ redis_ca_root_csr_file }} -subj "{{ cert_subject }}localhost"'
      creates: "{{ redis_ca_root_csr_file }}"
      title: Generate Redis CA CSR
    - command: 'openssl x509 -req -sha256 -days 365 -in {{ redis_ca_root_csr_file }} -signkey {{ redis_ca_root_key_file }} -out {{ redis_ca_root_certificate_file }}'
      creates: "{{ redis_ca_root_certificate_file }}"
      title: Generate Redis CA cert
    - title: Generate Redis key
      command: 'openssl ecparam -out {{ redis_cert_private_key_file }} -name prime256v1 -genkey'
      creates: "{{ redis_cert_private_key_file }}"
    - title: Generate a Redis CSR
      command: 'openssl req -new -sha256 -key {{ redis_cert_private_key_file }} -out {{ redis_cert_csr_file }} -subj "{{ cert_subject }}localhost"'
      creates: "{{ redis_cert_csr_file }}"
    - title: Generate the Redis cert
      command: 'openssl x509 -req -in {{ redis_cert_csr_file }} -CA {{ redis_ca_root_certificate_file }} -CAkey {{ redis_ca_root_key_file }} -CAcreateserial -out {{ redis_cert_certificate_file }} -days 365 -sha256'
      creates: "{{ redis_cert_certificate_file }}"
  loop_control:
    label: "{{ item.title }}"

- name: Render Redis ACL
  template:
    src: "redis-users.acl.j2"
    dest: "{{ redis_generated_dir }}/redis-users.acl"
    mode: '0600'
