- name: Render docker templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ sources_dest }}/{{ item }}"
    mode: '0600'
  loop:
    - docker-compose.yml
    - Dockerfile

- name: Render Redis ACL
  template:
    src: "redis-users.acl.j2"
    dest: "{{ sources_dest }}/redis-users.acl"
    mode: '0600'
