---
- name: Generate Redis Sentinel host list
  set_fact:
    redis_hosts: "{{ redis_hosts | default([]) + [ host_port ] }}"
  loop: "{{ query('sequence', 'start=1 end='+(redis_sentinel_sentinel_nodes)|string) }}"
  vars:
    hostname: "{{ redis_node_prefix }}sentinel-{{ item }}"
    host_port: "{{ hostname }}:{{ item }}{{ redis_exposed_port }}"

- name: Render Redis replica conf file
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_generated_dir }}/redis.replica.conf"
    mode: '0644'
  vars:
    is_replica: True

- name: Render Redis Sentinel ACL file
  template:
    src: "redis-users.acl.j2"
    dest: "{{ redis_generated_dir }}/redis-users-sentinel.acl"
    mode: '0644'
  vars:
    show_sentinel_user: False

- name: Create Redis sentinel directory
  file:
    state: directory
    mode: 0777
    path: "{{ redis_generated_dir }}/sentinel{{ item }}"
  loop: "{{ query('sequence', 'start=1 end='+(redis_sentinel_sentinel_nodes)|string) }}"

- name: Render Redis sentinel files
  template:
    src: "redis-sentinel.conf.j2"
    dest: "{{ redis_generated_dir }}/sentinel{{ item }}/sentinel.conf"
    mode: 0666
  vars:
    sentinel_port: "{{ item }}{{ redis_exposed_port }}"
    redis_node_number: "{{ item }}"
  loop: "{{ query('sequence', 'start=1 end='+(redis_sentinel_sentinel_nodes)|string) }}"

- name: Zero out replica volume directories
  include_tasks: volume_dirs.yml
  loop: "{{ query('sequence', 'start=1 end='+(redis_sentinel_replica_nodes)|string) }}"
  vars:
    volume_type: "replica"

- name: Zero out sentinel volume directories
  include_tasks: volume_dirs.yml
  loop: "{{ query('sequence', 'start=1 end='+(redis_sentinel_sentinel_nodes)|string) }}"
  vars:
    volume_type: "sentinel"
