---
- name: TACACS authenticator
  ansible.platform.authenticator:
    name: "{{ tacacs_container_name }}"
    slug: "{{ tacacs_container_name | replace(' ', '') | lower }}"
    enabled: True
    create_objects: True
    remove_users: True
    configuration: "{{ tacacs_configuration }}"
    type: "ansible_base.authentication.authenticator_plugins.tacacs"    

- name: TACACS authenticator org map
  ansible.platform.authenticator_map:
    name: "{{ tacacs_auth_map_name }} - org"
    authenticator: "{{ tacacs_container_name }}"
    map_type: "organization"
    organization: "Default"
    role: "Organization Member"
    order: 0
    triggers:
      always: {}
