---
tacacs_container_name: "Dev TACACS Container"
tacacs_auth_map_name: "Dev TACACS Authenticator Map"

tacacs_configuration:
  PORT: "{{ tacacs_exposed_tacacs_port }}"
  HOST: "tacacs"
  AUTH_PROTOCOL: "ascii"
  REM_ADDR: "true"
  SECRET: "ciscotacacskey"
  SESSION_TIMEOUT: "5"
