---
- name: Load certs, existing and new SAML settings
  set_fact:
    private_key: "{{ private_key_content }}"
    public_key: "{{ public_key_content }}"
  vars:
    # We add the extra \\ in here so that when jinja is templating out the files we end up with \n in the strings.
    public_key_content: "{{ lookup('file', public_key_file) | regex_replace('\n', '\\n') }}"
    private_key_content: "{{ lookup('file', private_key_file) | regex_replace('\n', '\\n') }}"

- name: SAML authenticator
  ansible.platform.authenticator:
    name: "{{ saml_adapter_name }}"
    slug: "{{ saml_slug }}"
    enabled: True
    create_objects: True
    remove_users: True
    configuration: "{{ saml_configuration }}"
    type: "ansible_base.authentication.authenticator_plugins.saml"    

- name: SAML authenticator superuser attribute map
  ansible.platform.authenticator_map:
    name: "{{ saml_auth_map_name }} - superuser"
    authenticator: "{{ saml_adapter_name }}"
    map_type: "is_superuser"
    order: 0
    triggers: "{\"attributes\":{\"is_superuser\": {}, \"join_condition\": \"or\"}}"

- name: SAML authenticator auditor attribute map
  ansible.platform.authenticator_map:
    name: "{{ saml_auth_map_name }} - auditor"
    authenticator: "{{ saml_adapter_name }}"
    map_type: "role"
    role: "Platform Auditor"
    order: 0
    triggers: "{\"attributes\":{\"is_system_auditor\": {}, \"join_condition\": \"or\"}}"

- name: SAML authenticator org map
  ansible.platform.authenticator_map:
    name: "{{ saml_auth_map_name }} - org"
    gateway_hostname: "{{ gateway_host }}"
    gateway_username: "{{ gateway_admin_username }}"
    gateway_password: "{{ gateway_admin_password }}"
    gateway_validate_certs: False
    authenticator: "{{ saml_adapter_name }}"
    map_type: "organization"
    role: "Organization Member"
    organization: "Default"
    order: 0
    triggers:
      always: {}
