---
- name: Load certs, existing and new SAML settings
  set_fact:
    oidc_public_key: "{{ lookup('file', public_key_cert) | regex_replace('\n', '') | regex_replace('-----[^-]*-----', '') }}"

- name: Install OIDC adapter
  include_tasks: plumb_oidc.yml

- name: Install SAML adapter
  include_tasks: plumb_saml.yml
