---
- name: OIDC authenticator
  ansible.gateway_configuration.authenticator:
    name: "{{ oidc_adapter_name }}"
    slug: "{{ oidc_adapter_name | replace(' ', '') | lower }}"
    enabled: True
    create_objects: True
    remove_users: True
    configuration: "{{ oidc_configuration }}"
    type: "ansible_base.authentication.authenticator_plugins.keycloak"

- name: OIDC authenticator attribute maps
  ansible.gateway_configuration.authenticator_map:
    name: "{{ oidc_auth_map_name }} - {{ item }}"
    authenticator: "{{ oidc_adapter_name }}"
    map_type: "{{ item }}"
    order: 0
    triggers: "{\"attributes\":{\"{{ item }}\": {}, \"join_condition\": \"or\"}}"
  loop: ["is_superuser", "is_system_auditor"]

- name: OIDC authenticator org map
  ansible.gateway_configuration.authenticator_map:
    name: "{{ oidc_auth_map_name }} - org"
    authenticator: "{{ oidc_adapter_name }}"
    map_type: "organization"
    organization: "Default"
    order: 0
    triggers:
      always: {}
