# django-ansible-base, RBAC and resource_registry highly involved here
from ansible_base.lib.utils.settings import get_setting
from ansible_base.rbac.api.serializers import RoleDefinitionSerializer, RoleTeamAssignmentSerializer
from ansible_base.rbac.api.views import (
    BaseAssignmentViewSet,
    RoleDefinitionViewSet,
    RoleTeamAssignmentViewSet,
    RoleUserAssignmentViewSet,
    TeamAccessAssignmentViewSet,
    TeamAccessViewSet,
    UserAccessAssignmentViewSet,
    UserAccessViewSet,
)
from ansible_base.rbac.policies import can_view_all_users
from ansible_base.rbac.remote import RemoteObject
from django.db import transaction
from django.utils.translation import gettext_lazy as _
from requests.exceptions import HTTPError
from rest_framework.exceptions import APIException, NotFound, ValidationError

from aap_gateway_api.models import ServiceAPIRoute

# aap-gateway imports
from aap_gateway_api.models.service_type import service_type_to_api_slug
from aap_gateway_api.utils.rbac import get_remote_object_filter_from_request, user_can_view_remote_rbac_object
from aap_gateway_api.utils.resources_client import GWResourceAPIClient

from .common import ResourceAllClientMixin, ResourceAPIUpdateMixin


class GatewayRoleDefinitionSerializer(RoleDefinitionSerializer):
    """Custom serializer with Gateway-specific validation

    Generated by Claude Sonnet 4
    """

    def validate(self, attrs):
        """Perform Gateway-specific validation before saving"""
        # Call parent validation first
        attrs = super().validate(attrs)

        # Only validate system roles (those with null content_type)
        content_type = attrs.get('content_type')
        if content_type is not None:
            return attrs

        # Check permissions for system roles
        permissions = attrs.get('permissions', [])
        invalid_permissions = []

        for permission in permissions:
            # Only allow galaxy service for system roles since galaxy resources are not bound
            # to an organization, which is challenging for galaxy-specific reasons
            if permission.content_type.service != 'galaxy':
                invalid_permissions.append(f"'{permission.codename}' (service: {permission.content_type.service})")

        if invalid_permissions:
            permissions_list = ", ".join(invalid_permissions)
            raise ValidationError(
                _("System roles can only have permissions for the 'galaxy' service. Invalid permissions: %(permissions)s") % {"permissions": permissions_list}
            )

        return attrs


class GatewayRoleDefinitionViewSet(ResourceAPIUpdateMixin, RoleDefinitionViewSet):
    serializer_class = GatewayRoleDefinitionSerializer


class GatewayRoleTeamAssignmentSerializer(RoleTeamAssignmentSerializer):
    """Custom serializer with Galaxy-specific validation for team role assignments

    Teams can only be assigned roles where all permissions are in the 'galaxy' service.
    Gateway overrides actor queryset so team visibility is enforced here
    rather than in DAB, since users/teams are owned by the resource provider.
    """

    def get_actor_queryset(self, requesting_user):
        from aap_gateway_api.utils.rbac import visible_teams

        return visible_teams(requesting_user)

    def validate(self, attrs):
        """Validate that team role assignments only use galaxy-only roles"""
        # Call parent validation first
        attrs = super().validate(attrs)

        # Get the role_definition being assigned
        role_definition = attrs.get('role_definition')

        if role_definition and (role_definition.content_type is None):
            # Check if all permissions for this role are in the galaxy service
            non_galaxy_permissions = []

            for permission in role_definition.permissions.all():
                if permission.content_type.service != 'galaxy':
                    non_galaxy_permissions.append(f"'{permission.codename}' (service: {permission.content_type.service})")

            if non_galaxy_permissions:
                permissions_list = ", ".join(non_galaxy_permissions)
                raise ValidationError(
                    _(
                        "Teams can only be assigned roles where all permissions are for the 'galaxy' service. "
                        "Role '%(role)s' has non-galaxy permissions: %(permissions)s"
                    )
                    % {"role": role_definition.name, "permissions": permissions_list}
                )

        return attrs


class ProxyAPIException(APIException):
    "If a service gave an error response, we wrap it up and pass it onto the client as if it was ours"

    def __init__(self, detail, status_code):
        self.detail = detail
        self.status_code = status_code


class AssignmentSyncMixin(ResourceAllClientMixin):
    def _is_owned_by_gateway(self, role_definition):
        """Any shared resource is owned by Gateway, return True in that case

        Return True in the case of a component-specific role_definition.
        This basically only applies to object-level roles.
        """
        if (role_definition is None) or (role_definition.content_type is None):
            # System roles are used by galaxy_ng now, but are not object-level
            # so they are still owned by Gateway
            return True
        # NOTE: right now "aap" is unused, but see aap_gateway_api.resource_api
        # aap is the service_type for resources specific to Gateway only
        return bool(role_definition.content_type.service in ('aap', 'shared'))

    def get_direct_client(self, role_definition):
        "This returns a single-service synchronous client, for service-specific assignments"
        service_type = role_definition.content_type.service
        service_name = service_type_to_api_slug(service_type)
        service = ServiceAPIRoute.objects.get(api_slug=service_name)
        return GWResourceAPIClient(service, user=self.request.user, raise_if_bad_request=True)

    def remote_sync_assignment(self, assignment):
        if self._is_owned_by_gateway(assignment.role_definition):
            self._resources_client.sync_assignment(assignment)
        else:
            client = self.get_direct_client(assignment.role_definition)
            try:
                client.sync_assignment(assignment)
            except HTTPError as e:
                try:
                    error_detail = e.response.json()
                except Exception:
                    error_detail = e.response.text
                raise ProxyAPIException(detail=error_detail, status_code=e.response.status_code)

    def remote_sync_unassignment(self, role_definition, actor, content_object):
        if self._is_owned_by_gateway(role_definition):
            self._resources_client.sync_unassignment(role_definition, actor, content_object)
        else:
            client = self.get_direct_client(role_definition)
            try:
                client.sync_unassignment(role_definition, actor, content_object)
            except HTTPError as e:
                try:
                    error_detail = e.response.json()
                except Exception:
                    error_detail = e.response.text
                raise ProxyAPIException(detail=error_detail, status_code=e.response.status_code)

    @transaction.atomic  # just making it atomic
    def perform_create(self, serializer):
        return super().perform_create(serializer)

    @transaction.atomic  # just making it atomic
    def perform_destroy(self, assignment):
        return super().perform_destroy(assignment)


class BypassVisibleItemsForPrivilegedUsersMixin:
    """Bypass ``BaseAssignmentViewSet.visible_items`` for remote objects.

    WORKAROUND for incomplete RoleEvaluation data (AAP-91996, AAP-70503).

    DAB's ``visible_items`` filters assignments by checking whether the user
    has *any* ``RoleEvaluation`` row for the same ``(content_type, object_id)``.
    For remote objects this is incomplete because ``ObjectRole.parent_reference``
    is never populated through the public/service API, preventing org-level
    evaluations from propagating to child objects.

    When the request targets a specific remote object (``object_id`` +
    content-type query params), this mixin delegates to
    ``user_can_view_remote_rbac_object`` which re-derives visibility from
    locally available data.  DRF filter backends still narrow the queryset by
    the same query params, so the bypass does not expose unrelated assignments.

    See ``aap_gateway_api.utils.rbac.user_can_view_remote_rbac_object`` for
    the full list of checks and their rationale.
    """

    def _bypass_visible_items(self):
        if can_view_all_users(self.request.user):
            return True
        object_id, content_type = get_remote_object_filter_from_request(self.request)
        if object_id and content_type:
            return user_can_view_remote_rbac_object(self.request.user, content_type, object_id)
        return False

    def filter_queryset(self, qs):
        if self._bypass_visible_items():
            return super(BaseAssignmentViewSet, self).filter_queryset(qs)
        return super().filter_queryset(qs)


class GatewayAccessURLMixin:
    """Override permission gate and queryset for remote object access lists.

    WORKAROUND for incomplete RoleEvaluation data (AAP-91996).

    DAB's access-list views rely on two evaluation-based paths:
    1. ``check_permission_to_object`` — gates entry via ``has_obj_perm``
    2. ``get_queryset`` — builds the result set from ``RoleEvaluation`` rows

    Both fail for remote objects when ``parent_reference`` is missing on the
    ``ObjectRole`` (see ``user_can_view_remote_rbac_object`` docstring for root
    cause).  This mixin overrides both: the gate uses the gateway workaround
    check, and ``get_queryset`` falls back to a direct assignment lookup when
    the evaluation-based queryset is empty for remote objects.
    """

    def check_permission_to_object(self, obj):
        if isinstance(obj, RemoteObject) and not get_setting('ANSIBLE_BASE_ENFORCE_REMOTE_OBJECT_PERMISSIONS', True):
            if user_can_view_remote_rbac_object(self.request.user, obj.content_type, obj.object_id):
                return
            raise NotFound
        return super().check_permission_to_object(obj)

    def get_queryset(self):
        qs = super().get_queryset()
        if qs.exists():
            return qs

        if not hasattr(self, 'related_object') or not isinstance(self.related_object, RemoteObject):
            return qs
        if get_setting('ANSIBLE_BASE_ENFORCE_REMOTE_OBJECT_PERMISSIONS', True):
            return qs

        from ansible_base.rbac.models import RoleTeamAssignment, RoleUserAssignment

        obj = self.related_object
        ct = self.content_type
        actor_cls = self.get_actor_model()
        actor_field = 'user_id' if actor_cls._meta.model_name == 'user' else 'team_id'
        assignment_cls = RoleUserAssignment if actor_cls._meta.model_name == 'user' else RoleTeamAssignment

        actor_ids = assignment_cls.objects.filter(
            content_type=ct,
            object_id=str(obj.pk),
        ).values_list(actor_field, flat=True)

        return actor_cls.objects.filter(pk__in=actor_ids)


class GatewayUserAccessViewSet(GatewayAccessURLMixin, UserAccessViewSet):
    pass


class GatewayTeamAccessViewSet(GatewayAccessURLMixin, TeamAccessViewSet):
    pass


class GatewayUserAccessAssignmentViewSet(GatewayAccessURLMixin, UserAccessAssignmentViewSet):
    pass


class GatewayTeamAccessAssignmentViewSet(GatewayAccessURLMixin, TeamAccessAssignmentViewSet):
    pass


class GatewayRoleUserAssignmentViewSet(BypassVisibleItemsForPrivilegedUsersMixin, AssignmentSyncMixin, RoleUserAssignmentViewSet):
    """ViewSet for managing user role assignments with upstream service synchronization."""


class GatewayRoleTeamAssignmentViewSet(BypassVisibleItemsForPrivilegedUsersMixin, AssignmentSyncMixin, RoleTeamAssignmentViewSet):
    serializer_class = GatewayRoleTeamAssignmentSerializer
