# django-ansible-base, RBAC and resource_registry highly involved here
import logging

from ansible_base.rbac.api.serializers import RoleDefinitionSerializer, RoleTeamAssignmentSerializer
from ansible_base.rbac.api.views import BaseAssignmentViewSet, RoleDefinitionViewSet, RoleTeamAssignmentViewSet, RoleUserAssignmentViewSet
from ansible_base.rbac.policies import can_view_all_users, check_content_obj_permission
from ansible_base.rbac.validators import check_locally_managed
from django.db import transaction
from django.utils.translation import gettext_lazy as _
from requests.exceptions import HTTPError
from rest_framework.exceptions import APIException, ValidationError

from aap_gateway_api.models import ServiceAPIRoute

# aap-gateway imports
from aap_gateway_api.models.service_type import service_type_to_api_slug
from aap_gateway_api.utils.resources_client import GWResourceAPIClient

from .common import ResourceAllClientMixin, ResourceAPIUpdateMixin

logger = logging.getLogger('aap_gateway_api.views.api.v1.role')


class GatewayRoleDefinitionSerializer(RoleDefinitionSerializer):
    """Custom serializer with Gateway-specific validation

    Generated by Claude Sonnet 4
    """

    def validate(self, attrs):
        """Perform Gateway-specific validation before saving"""
        # Call parent validation first
        attrs = super().validate(attrs)

        # Only validate system roles (those with null content_type)
        content_type = attrs.get('content_type')
        if content_type is not None:
            return attrs

        # Check permissions for system roles
        permissions = attrs.get('permissions', [])
        invalid_permissions = []

        for permission in permissions:
            # Only allow galaxy service for system roles since galaxy resources are not bound
            # to an organization, which is challenging for galaxy-specific reasons
            if permission.content_type.service != 'galaxy':
                invalid_permissions.append(f"'{permission.codename}' (service: {permission.content_type.service})")

        if invalid_permissions:
            permissions_list = ", ".join(invalid_permissions)
            raise ValidationError(
                _("System roles can only have permissions for the 'galaxy' service. Invalid permissions: %(permissions)s") % {"permissions": permissions_list}
            )

        return attrs


class GatewayRoleDefinitionViewSet(ResourceAPIUpdateMixin, RoleDefinitionViewSet):
    serializer_class = GatewayRoleDefinitionSerializer


class GatewayRoleTeamAssignmentSerializer(RoleTeamAssignmentSerializer):
    """Custom serializer with Galaxy-specific validation for team role assignments

    Teams can only be assigned roles where all permissions are in the 'galaxy' service.
    Gateway overrides actor queryset so team visibility is enforced here
    rather than in DAB, since users/teams are owned by the resource provider.
    """

    def get_actor_queryset(self, requesting_user):
        from aap_gateway_api.utils.rbac import visible_teams

        return visible_teams(requesting_user)

    def validate(self, attrs):
        """Validate that team role assignments only use galaxy-only roles"""
        # Call parent validation first
        attrs = super().validate(attrs)

        # Get the role_definition being assigned
        role_definition = attrs.get('role_definition')

        if role_definition and (role_definition.content_type is None):
            # Check if all permissions for this role are in the galaxy service
            non_galaxy_permissions = []

            for permission in role_definition.permissions.all():
                if permission.content_type.service != 'galaxy':
                    non_galaxy_permissions.append(f"'{permission.codename}' (service: {permission.content_type.service})")

            if non_galaxy_permissions:
                permissions_list = ", ".join(non_galaxy_permissions)
                raise ValidationError(
                    _(
                        "Teams can only be assigned roles where all permissions are for the 'galaxy' service. "
                        "Role '%(role)s' has non-galaxy permissions: %(permissions)s"
                    )
                    % {"role": role_definition.name, "permissions": permissions_list}
                )

        return attrs


class ProxyAPIException(APIException):
    "If a service gave an error response, we wrap it up and pass it onto the client as if it was ours"

    def __init__(self, detail, status_code):
        self.detail = detail
        self.status_code = status_code


class AssignmentSyncMixin(ResourceAllClientMixin):
    def _is_owned_by_gateway(self, role_definition):
        """Any shared resource is owned by Gateway, return True in that case

        Return True in the case of a component-specific role_definition.
        This basically only applies to object-level roles.
        """
        if (role_definition is None) or (role_definition.content_type is None):
            # System roles are used by galaxy_ng now, but are not object-level
            # so they are still owned by Gateway
            return True
        # NOTE: right now "aap" is unused, but see aap_gateway_api.resource_api
        # aap is the service_type for resources specific to Gateway only
        return bool(role_definition.content_type.service in ('aap', 'shared'))

    def get_direct_client(self, role_definition):
        "This returns a single-service synchronous client, for service-specific assignments"
        service_type = role_definition.content_type.service
        service_name = service_type_to_api_slug(service_type)
        service = ServiceAPIRoute.objects.get(api_slug=service_name)
        return GWResourceAPIClient(service, user=self.request.user, raise_if_bad_request=True)

    def _pre_sync_to_service(self, serializer, obj=None):
        """Sync assignment to the owning service BEFORE local creation.

        For service-owned resources, the service knows the parent organization.
        Returns the content object with parent_reference set from the service response.
        """
        rd = serializer.validated_data['role_definition']
        client = self.get_direct_client(rd)

        data = {'role_definition': rd.name}

        actor = serializer.validated_data.get('user') or serializer.validated_data.get('team')
        actor_type = 'user' if serializer.Meta.model._meta.model_name == 'roleuserassignment' else 'team'
        data[f'{actor_type}_ansible_id'] = str(actor.resource.ansible_id)

        if obj is None:
            obj = serializer.get_object_from_data(serializer.validated_data, rd, self.request.user)
        if obj is not None:
            data['object_id'] = str(obj.pk)

        if self.request.user and hasattr(self.request.user, 'resource'):
            data['created_by_ansible_id'] = str(self.request.user.resource.ansible_id)

        try:
            response = client._sync_assignment(data)
            response_data = response.json()
            parent_reference = response_data.get('parent_reference', '')
            if parent_reference and obj is not None:
                obj.parent_reference = parent_reference
        except HTTPError as e:
            try:
                error_detail = e.response.json()
            except Exception:
                error_detail = e.response.text
            raise ProxyAPIException(detail=error_detail, status_code=e.response.status_code)

        return obj

    def remote_sync_assignment(self, assignment):
        if self._is_owned_by_gateway(assignment.role_definition):
            self._resources_client.sync_assignment(assignment)

    def remote_sync_unassignment(self, role_definition, actor, content_object):
        if self._is_owned_by_gateway(role_definition):
            self._resources_client.sync_unassignment(role_definition, actor, content_object)
        else:
            client = self.get_direct_client(role_definition)
            try:
                client.sync_unassignment(role_definition, actor, content_object)
            except HTTPError as e:
                try:
                    error_detail = e.response.json()
                except Exception:
                    error_detail = e.response.text
                raise ProxyAPIException(detail=error_detail, status_code=e.response.status_code)

    @transaction.atomic
    def perform_create(self, serializer):
        rd = serializer.validated_data.get('role_definition')

        if rd and not self._is_owned_by_gateway(rd):
            requesting_user = self.request.user
            actor = serializer.validated_data.get('user') or serializer.validated_data.get('team')
            obj = serializer.get_object_from_data(serializer.validated_data, rd, requesting_user)

            # Run the same DAB checks BaseAssignmentSerializer.create() would,
            # before syncing to the owning service (avoids creating upstream
            # assignments that local authz would reject).
            if obj is not None and getattr(obj, 'validate_role_assignment', None):
                obj.validate_role_assignment(actor, rd, requesting_user=requesting_user)
            check_locally_managed(rd)
            if not obj:
                raise ValidationError({'object_id': _('Object must be specified for this role assignment')})
            check_content_obj_permission(requesting_user, obj)

            obj = self._pre_sync_to_service(serializer, obj=obj)

            with transaction.atomic():
                assignment = rd.give_permission(actor, obj)
            serializer.instance = assignment
            return assignment

        return super().perform_create(serializer)

    @transaction.atomic
    def perform_destroy(self, assignment):
        return super().perform_destroy(assignment)


class BypassVisibleItemsForPrivilegedUsersMixin:
    """Bypasses BaseAssignmentViewSet's visible_items filter for callers who
    can view all users (superusers and org admins when
    ORG_ADMINS_CAN_SEE_ALL_USERS is enabled).

    The gateway does not enforce remote object permissions
    (ANSIBLE_BASE_ENFORCE_REMOTE_OBJECT_PERMISSIONS=False), so the
    RoleEvaluation cache that visible_items relies on is incomplete for
    remote objects (e.g. AWX job templates).  That causes visible_items
    to hide assignments the privileged user should see.

    DRF filter backends still apply query-param filtering (object_id,
    content_type, etc.).
    """

    def filter_queryset(self, qs):
        if can_view_all_users(self.request.user):
            return super(BaseAssignmentViewSet, self).filter_queryset(qs)
        return super().filter_queryset(qs)


class GatewayRoleUserAssignmentViewSet(BypassVisibleItemsForPrivilegedUsersMixin, AssignmentSyncMixin, RoleUserAssignmentViewSet):
    """ViewSet for managing user role assignments with upstream service synchronization."""


class GatewayRoleTeamAssignmentViewSet(BypassVisibleItemsForPrivilegedUsersMixin, AssignmentSyncMixin, RoleTeamAssignmentViewSet):
    serializer_class = GatewayRoleTeamAssignmentSerializer
