---
- name: Load the existing LDAP authenticators
  uri:
    url: "{{ gateway_host }}/api/gateway/v1/authenticators/?name={{ ldap_container_name | urlencode }}"
    validate_certs: False
    url_username: "{{ gateway_admin_username }}"
    url_password: "{{ gateway_admin_password }}"
    force_basic_auth: True
  register: existing_authenticators

- block:
    - name: Display existing LDAP authenticators
      debug:
        msg:
          - "Existing authenticator"
          - "{{ existing_authenticators.json.results[0] }}"

    - name: Write out the existing content
      copy:
        dest: "../generated/existing_ldap_adapter_settings.json"
        content: "{{ existing_authenticators.json.results[0] }}"

    - name: Updating existing authenticator
      uri:
        url: "{{ gateway_host }}/api/gateway/v1/authenticators/{{ existing_authenticators.json.results[0].id }}/"
        method: PUT
        body: "{{ ldap_configuration }}"
        body_format: json
        validate_certs: False
        url_username: "{{ gateway_admin_username }}"
        url_password: "{{ gateway_admin_password }}"
        force_basic_auth: True
      changed_when: True

  when: existing_authenticators.json.count != 0

- name: Configure a new authenticator
  uri:
    url: "{{ gateway_host }}/api/gateway/v1/authenticators/"
    method: POST
    body: "{{ ldap_configuration }}"
    body_format: json
    validate_certs: False
    url_username: "{{ gateway_admin_username }}"
    url_password: "{{ gateway_admin_password }}"
    force_basic_auth: True
    status_code:
      - 201
  changed_when: True
  when: existing_authenticators.json.count == 0
