---
- name: LDAP authenticator
  ansible.platform.authenticator:
    name: "{{ ldap_container_name }}"
    slug: "{{ ldap_container_name | replace(' ', '') | lower }}"
    enabled: True
    create_objects: True
    remove_users: True
    configuration: "{{ ldap_configuration }}"
    type: "ansible_base.authentication.authenticator_plugins.ldap"

- name: "LDAP authenticator group mappings"
  ansible.platform.authenticator_map:
    name: "{{ ldap_auth_map_name }}-{{ item.ldap_group }}"
    authenticator: "{{ ldap_container_name }}"
    map_type: "{{ item.map_type }}"
    role: "{{ item.role | default('') }}"
    order: 0
    triggers: "{\"groups\":{\"{{ item.trigger_type }}\":[\"cn={{ item.ldap_group }},ou=groups,dc=example,dc=org\"]}}"
  loop_control:
    label: "{{ item.ldap_group }}"
  loop: "{{ ldap_group_mappings }}"

- name: LDAP authenticator map - org admins
  ansible.platform.authenticator_map:
    name: "{{ ldap_auth_map_name }}"
    authenticator: "{{ ldap_container_name }}"
    map_type: "team"
    role: "Team Member"
    organization: "LDAP Organization"
    team: "Organization Admins"
    order: 0
    triggers:
      "groups":
        "has_or":
          - "cn=org_admins,ou=groups,dc=example,dc=org"

- name: LDAP authenticator map - all users
  ansible.platform.authenticator_map:
    name: "{{ ldap_auth_map_name }}"
    authenticator: "{{ ldap_container_name }}"
    map_type: "team"
    role: "Team Member"
    organization: "LDAP Organization"
    team: "Organization Users"
    order: 0
    triggers:
      "always": {}

- name: LDAP Union authenticator
  ansible.platform.authenticator:
    name: "{{ ldap_container_name }} Union"
    slug: "{{ ldap_container_name | replace(' ', '') | lower }}union"
    enabled: False
    create_objects: True
    remove_users: True
    configuration: "{{ ldap_configuration | combine({'USER_SEARCH': union_user_search}) | ansible.utils.remove_keys('USER_DN_TEMPLATE') }}"
    type: "ansible_base.authentication.authenticator_plugins.ldap"
  vars:
    union_user_search: [
      [
        "ou=users,dc=example,dc=org",
        "SCOPE_SUBTREE",
        "(cn=%(user)s)"
      ],
      [
        "ou=other_users,dc=example,dc=org",
        "SCOPE_SUBTREE",
        "(cn=%(user)s)"
      ]
    ]

- name: "LDAP Union authenticator group mappings"
  ansible.platform.authenticator_map:
    name: "{{ ldap_auth_map_name }}-{{ item.ldap_group }}"
    authenticator: "{{ ldap_container_name }} Union"
    map_type: "{{ item.map_type }}"
    role: "{{ item.role | default('') }}"
    order: 0
    triggers: "{\"groups\":{\"{{ item.trigger_type }}\":[\"cn={{ item.ldap_group }},ou=groups,dc=example,dc=org\"]}}"
  loop_control:
    label: "{{ item.ldap_group }}"
  loop: "{{ ldap_group_mappings }}"

- name: LDAP Union authenticator map - org admins
  ansible.platform.authenticator_map:
    name: "{{ ldap_auth_map_name }}"
    authenticator: "{{ ldap_container_name }} Union"
    map_type: "team"
    role: "Team Member"
    organization: "LDAP Organization"
    team: "Organization Admins"
    order: 0
    triggers:
      "groups":
        "has_or":
          - "cn=org_admins,ou=groups,dc=example,dc=org"

- name: LDAP Union authenticator map - all users
  ansible.platform.authenticator_map:
    name: "{{ ldap_auth_map_name }}"
    authenticator: "{{ ldap_container_name }} Union"
    map_type: "team"
    role: "Team Member"
    organization: "LDAP Organization"
    team: "Organization Users"
    order: 0
    triggers:
      "always": {}
