"""
Django settings for project aap_gateway_api.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from split_settings.tools import include, optional

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '%(asctime)s %(levelname)-8s %(name)s %(message)s'},
    },
    'handlers': {
        'console': {
            '()': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {'handlers': ['console']},
        'django.request': {
            'handlers': [
                'console',
            ],
            'level': 'WARNING',
        },
        "django_auth_ldap": {
            'handlers': [
                'console',
            ],
            'level': 'INFO',
            'propagate': True,
        },
        'rest_framework.request': {
            'handlers': [
                'console',
            ],
            'level': 'WARNING',
            'propagate': False,
        },
        'py.warnings': {'handlers': ['console']},
        'aap': {
            'handlers': [
                'console',
            ],
            'level': 'WARNING',
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dynamic_preferences',
    'django_extensions',
    'rest_framework',
    'aap_gateway_api',
    'django_grpc',
    'ansible_base',
]

# User our own user model
AUTH_USER_MODEL = 'aap_gateway_api.User'

AUTHENTICATION_BACKENDS = [
    "ansible_base.authentication.backends.GatewayAuth",
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # NOTE: Do NOT put the built-in DRF SessionAuthentication here first,
        # or anything that doesn't return a string from its authenticate_header.
        # DRF uses the first thing here to determine if invalid auth should be
        # 401 or 403. The UI expects 401.
        'aap_gateway_api.authentication.session.SessionAuthentication',
        'aap_gateway_api.authentication.basic_auth.LoggedBasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

ROOT_URLCONF = 'aap_gateway_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'aap_gateway_api', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'aap_gateway_api.context_processors.version',
            ],
        },
    },
]

WSGI_APPLICATION = 'aap_gateway_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DATABASE_NAME"),
        "USER": os.environ.get("DATABASE_USER"),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD"),
        "HOST": os.environ.get("DATABASE_HOST"),
        "PORT": os.getenv("DATABASE_PORT", 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = '/opt/aap_gateway/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/api/login/'

LOG_ROOT = '/var/log/gateway/'

# Disallow sending session cookies over insecure connections
SESSION_COOKIE_SECURE = True

# Seconds before sessions expire.
# Note: This setting may be overridden by database settings.
SESSION_COOKIE_AGE = 1800

SESSION_COOKIE_NAME = 'gateway_sessionid'

# Time in seconds that the gateway access tokens are valid for.
GATEWAY_ACCESS_TOKEN_EXIPIRATION = 600

# Disallow sending csrf cookies over insecure connections
CSRF_COOKIE_SECURE = True

# Make this unique, and don't share it with anybody.
secret_key_file = '/etc/gateway/SECRET_KEY'
read_key = False
try:
    with open(secret_key_file, 'rb') as f:
        SECRET_KEY = f.read().strip()
    read_key = True
except FileNotFoundError:
    print(f"Failed to load file {secret_key_file}, will use default")
except PermissionError:
    print(f"Unable to read {secret_key_file}, will use default")
except Exception as e:
    print(f"Unhandled exception when reading {secret_key_file}, will use default, ({e.__class__}): {e}")
if not read_key:
    SECRET_KEY = 'django-insecure-aa$p$j(w3+l)77o3d4hb^_qoed!#!$d0g*t1%4a$x7gtrezoio'

DYNAMIC_PREFERENCES = {
    'REGISTRY_MODULE': 'preferences',
    'ENABLE_CACHE': False,
    'ENABLE_GLOBAL_MODEL_AUTO_REGISTRATION': False,
}

GRPCSERVER = {
    'servicers': ['aap_gateway_api.proxy.control_plane.grpc_hook'],  # see `grpc_hook()` below
    # 'interceptors': ['dotted.path.to.interceptor_class',],  # optional, interceprots are similar to middleware in Django
    'maximum_concurrent_rpcs': None,
    # optional, list of key-value pairs to configure the channel. The full list of available channel
    # arguments: https://grpc.github.io/grpc/core/group__grpc__arg__keys.html
    # 'options': [("grpc.max_receive_message_length", 1024 * 1024 * 100)],
    # 'credentials': [{
    #     'private_key': 'private_key.pem',
    #     'certificate_chain': 'certificate_chain.pem'
    # }],    # required only if SSL/TLS support is required to be enabled
    'async': True,  # Default: False, if True then gRPC server will start in ASYNC mode
}

include(optional('settings_dev.py'), scope=locals())
