"""
Django settings for project aap_gateway_api.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import socket
from pathlib import Path

from split_settings.tools import include, optional

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '%(asctime)s %(levelname)-8s %(name)s %(message)s'},
    },
    'handlers': {
        'console': {
            '()': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {'handlers': ['console']},
        'django.request': {
            'handlers': [
                'console',
            ],
            'level': 'WARNING',
        },
        "django_auth_ldap": {
            'handlers': [
                'console',
            ],
            'level': 'INFO',
            'propagate': True,
        },
        'rest_framework.request': {
            'handlers': [
                'console',
            ],
            'level': 'WARNING',
            'propagate': False,
        },
        'py.warnings': {'handlers': ['console']},
        'aap': {
            'handlers': [
                'console',
            ],
            'level': 'WARNING',
        },
        'ansible_base': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dynamic_preferences',
    'django_extensions',
    'rest_framework',
    'aap_gateway_api',
    'ansible_base.authentication',
    'ansible_base.rest_filters',
    'ansible_base.api_documentation',
    'ansible_base.resource_registry',
]

# User our own user model
AUTH_USER_MODEL = 'aap_gateway_api.User'
# Set our own Team model
ANSIBLE_BASE_TEAM_MODEL = 'aap_gateway_api.Team'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'aap_gateway_api.authentication.basic_auth.LoggedBasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'EXCEPTION_HANDLER': 'aap_gateway_api.views.gateway_exception_handler',
    'PAGE_SIZE': 50,
}

ROOT_URLCONF = 'aap_gateway_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'aap_gateway_api', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'aap_gateway_api.context_processors.version',
            ],
        },
    },
]

WSGI_APPLICATION = 'aap_gateway_api.wsgi.application'

# This is a gateway system account that gets created. If you change this after
# the account is created, you will need to manually update the username of the
# account to match.
#
# We use an underscore prefix to make it less likely to conflict with a real
# user.
SYSTEM_USERNAME = '_system'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DATABASE_NAME"),
        "USER": os.environ.get("DATABASE_USER"),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD"),
        "HOST": os.environ.get("DATABASE_HOST"),
        "PORT": os.getenv("DATABASE_PORT", 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.environ.get('GATEWAY_STATIC_ROOT', '/opt/aap_gateway/static/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/api/login/'

LOG_ROOT = '/var/log/gateway/'

# Disallow sending session cookies over insecure connections
SESSION_COOKIE_SECURE = True
# Seconds before sessions expire.
# Note: This setting may be overridden by database settings.
SESSION_COOKIE_AGE = 1800
SESSION_COOKIE_NAME = 'gateway_sessionid'
SESSION_ENGINE = "ansible_base.lib.sessions.stores.cached_dynamic_timeout"
SESSION_COOKIE_HTTPONLY = True

# Time in seconds that the gateway access tokens are valid for.
GATEWAY_ACCESS_TOKEN_EXIPIRATION = 600

# Disallow sending csrf cookies over insecure connections
CSRF_COOKIE_SECURE = True

CLUSTER_HOST_ID = socket.gethostname()

# Make this unique, and don't share it with anybody.
secret_key_file = os.environ.get('GATEWAY_SECRET_KEY_FILE', '/etc/gateway/SECRET_KEY')
read_key = False
try:
    with open(secret_key_file, 'rb') as f:
        SECRET_KEY = f.read().strip()
    read_key = True
except FileNotFoundError:
    print(f"Failed to load file {secret_key_file}, will use default")
except PermissionError:
    print(f"Unable to read {secret_key_file}, will use default")
except Exception as e:
    print(f"Unhandled exception when reading {secret_key_file}, will use default, ({e.__class__}): {e}")
if not read_key:
    SECRET_KEY = 'django-insecure-aa$p$j(w3+l)77o3d4hb^_qoed!#!$d0g*t1%4a$x7gtrezoio'

GATEWAY_CERT_FILE = os.environ.get('GATEWAY_CERT_FILE', '/etc/gateway/gateway.crt')
GATEWAY_KEY_FILE = os.environ.get('GATEWAY_KEY_FILE', '/etc/gateway/gateway.key')
GATEWAY_PATH_REWRITE_SCRIPT_FILE = os.environ.get('GATEWAY_PATH_REWRITE_SCRIPT_FILE', '/etc/envoy/envoy-path-rewrite.lua')

using_cache = True
for env_var in ['REDIS_USER', 'REDIS_PASS', 'REDIS_HOST', 'REDIS_PORT']:
    if os.environ.get(env_var, None) is None:
        using_cache = False
        print(f"Warning, missing {env_var}")

if using_cache:
    redis_url = f"redis://{os.environ.get('REDIS_USER')}:{os.environ.get('REDIS_PASS')}@{os.environ.get('REDIS_HOST')}:{os.environ.get('REDIS_PORT')}"
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": redis_url,
        }
    }
else:
    print("===================================================================================")
    print("|                                                                                 |")
    print("|   WARNING: Redis cache is disabled, defaulting to memory cache.                 |")
    print("|            Note: this is not a valid configuration for a clustered environment. |")
    print("|                                                                                 |")
    print("===================================================================================")
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "not-optimal",
        }
    }


DYNAMIC_PREFERENCES = {
    'REGISTRY_MODULE': 'preferences',
    'ENABLE_CACHE': using_cache,
    'ENABLE_GLOBAL_MODEL_AUTO_REGISTRATION': False,
}

include(optional('settings_dev.py'), scope=locals())

SPECTACULAR_SETTINGS = {
    'TITLE': 'AAP gateway API',
    'DESCRIPTION': 'AAP gateway API',
    'VERSION': 'v1',
    'SCHEMA_PATH_PREFIX': '/api/gateway/v1/',
}

ANSIBLE_BASE_SOCIAL_AUTH_STRATEGY_SETTINGS_FUNCTION = "aap_gateway_api.authentication.util.load_social_auth_settings"

ANSIBLE_BASE_SETTINGS_FUNCTION = 'aap_gateway_api.utils.preferences.get_setting'

ANSIBLE_BASE_RESOURCE_CONFIG_MODULE = "aap_gateway_api.resource_api"

ANSIBLE_BASE_ORGANIZATION_MODEL = 'aap_gateway_api.Organization'
ANSIBLE_BASE_TEAM_MODEL = 'aap_gateway_api.Team'

ANSIBLE_BASE_PRODUCT_VERSION_FUNCTION = 'aap_gateway_api.version.get_api_version'
ANSIBLE_BASE_PRODUCT_NAME = 'AAP gateway'
ANSIBLE_BASE_USER_VIEWSET = 'aap_gateway_api.views.UserViewSet'

from ansible_base.lib import dynamic_config  # noqa: E402

settings_file = os.path.join(os.path.dirname(dynamic_config.__file__), 'dynamic_settings.py')
include(settings_file)


# NEVER remove anything from this list.
# https://docs.djangoproject.com/en/5.0/topics/auth/passwords/#password-upgrading
PASSWORD_HASHERS = [
    "aap_gateway_api.authentication.hashers.OwaspRecommendedArgon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

GRPC_SERVER_PROCESSES = 5
GRPC_SERVER_MAX_THREADS_PER_PROCESS = 10
GRPC_SERVER_PORT = "50051"
GRPC_SERVER_AUTH_SERVICE_TIMEOUT = "10s"

# Load settings from the global settings file if specified in the
# environment, defaulting to /etc/gateway/settings.py.
include(optional(os.environ.get('GATEWAY_SETTINGS_FILE', '/etc/gateway/settings.py')), scope=locals())
