__all__ = ['get_api_version']


def generate_version():
    import os

    current_dir = os.path.dirname(os.path.abspath(__file__))
    version_file = os.path.join(current_dir, '..', 'VERSION')

    if os.path.exists(version_file):
        with open(version_file, 'r') as file:
            return file.read().strip()
    else:
        try:
            from setuptools_scm import get_version

            return get_version()
        except ModuleNotFoundError:
            return "Unknown"


def get_api_version():
    """
    Return version as reported by aap-gateway/VERSION, if it exists,
    otherwise fall back to the package version, then fall back to
    a version string generated by setuptools_scm.
    """
    try:
        from importlib.metadata import version

        return version('aap-gateway')
    except Exception:
        return generate_version()


def get_aap_version() -> str:
    """
    Get x.y version of get_api_version() output.

    This should be equivalent to the AAP release the api version is a part of.
    """
    full_version = get_api_version()

    full_version_split = full_version.split(".")
    if len(full_version_split) < 2:
        return full_version
    return ".".join(full_version_split[:2])
