---
gateway_host: https://localhost:8000
gateway_validate_certs: False
gateway_admin_username: admin
gateway_admin_password: admin
container_reference: 'localhost'
# keycloak_enabled: True
# ldap_enabled: True
# tacacs_enabled: True
