upstream uwsgi {
    server localhost:8050;
}

server {
    listen 8000 default_server;
    server_name _;

    location /static/ {
        alias /opt/gateway/public/static/;
    }

    location / {
        uwsgi_pass uwsgi;
        include /etc/nginx/uwsgi_params;
    }
}
