### Init by Django command `gateway-manage register-service --config proxy.yml`
proxy:
  use_tls: true
  api_port: 9080

# Dictionary of services to be served under /api/<key>/.
services:
  gateway:
    use_tls: true
    api_port: 8000
    control_plane_port: 50051
    service_root: /
    type: gateway
    order: 100
    nodes:
      - address: "gateway"

  hub:
    use_tls: true
    service_root: /api/galaxy/
    api_port: 5043
    type: hub
    order: 1
    nodes:
      - address: "localhost"

  controller:
    use_tls: true
    service_root: /api/
    api_port: 8043
    type: controller
    order: 2
    nodes:
      - address: "localhost"

  eda:
    use_tls: true
    service_root: /api/
    api_port: 8000
    type: eda
    order: 3
    nodes:
      - address: "localhost"
