port 0
tls-port 6380
aclfile /usr/local/etc/redis/redis-users.acl
tls-cert-file /usr/local/etc/redis/redis.cert
tls-key-file /usr/local/etc/redis/redis.key
tls-ca-cert-file /usr/local/etc/redis/ca.cert
tls-auth-clients no
