---
name: CI
on:
  pull_request:
  push:
    branches:
      - devel
env:
  # Prevent SonarCloud from running on PRs from forks
  TARGET_REPOSITORY: 'ansible-automation-platform/aap-gateway'
jobs:
  tox:
    name: aap_gateway_api - ${{ matrix.tests.env }}
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    permissions:
      packages: write
      contents: read
      actions: write
    strategy:
      fail-fast: false
      matrix:
        tests:
          - env: check
            python-version: "3.11"
            sonar: false
            junit-xml-upload: false
          - env: check-migrations
            python-version: "3.11"
            sonar: false
            junit-xml-upload: false
          - env: check-oauth2-permissions
            python-version: "3.11"
            sonar: false
            junit-xml-upload: false
          - env: py311
            python-version: "3.11"
            sonar: true
            junit-xml-upload: true
    steps:
      - uses: actions/checkout@v3

      - name: Install build requirements
        run: sudo apt-get update && sudo apt-get install -y libsasl2-dev libldap2-dev libssl-dev libxmlsec1-dev

      - name: Install python ${{ matrix.tests.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.tests.python-version }}

      - name: Install tox
        run: pip${{ matrix.tests.python-version }} install tox tox-docker requests

      - name: Checkout DAB branch if needed
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tools/scripts/get_dab_for_pr.py

      - name: Run tox
        env:
          PYTEST_NUM_PROCESSES: 1
        run: tox -e ${{ matrix.tests.env }}

      - name: Inject PR number into coverage.xml
        if: matrix.tests.sonar
        run: sed -i '2i <!-- PR ${{ github.event.number }} -->' coverage.xml

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        if: matrix.tests.sonar
        with:
          name: coverage
          path: coverage.xml

      - name: Trigger SonarCloud Analysis
        if: |
          matrix.tests.junit-xml-upload &&
          github.event_name == 'push' &&
          github.repository == env.TARGET_REPOSITORY
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'sonar-pr.yml',
              ref: context.ref,
              inputs: {
                pr_number: '0',
                event_type: 'push',
                commit_sha: context.sha,
                repository: context.repo.owner + '/' + context.repo.repo,
                ci_run_id: context.runId.toString()
              }
            });

      - name: Upload jUnit XML test results
        if: |
          matrix.tests.junit-xml-upload &&
          github.event_name == 'push' &&
          github.repository == env.TARGET_REPOSITORY
        continue-on-error: true
        run: >-
          curl -v --user "${{ vars.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_USER }}:${{ secrets.PDE_ORG_RESULTS_UPLOAD_PASSWORD }}"
          --form "xunit_xml=@aap-gateway-test-results.xml"
          --form "component_name=aap-gateway"
          --form "git_commit_sha=${{ github.sha }}"
          --form "git_repository_url=https://github.com/${{ github.repository }}"
          "${{ vars.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL }}/api/results/upload/"
