---
name: collection tests
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  no_collection_files_allowed:
    name: Ensure no collection files are in PR
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get all changed collection files
        id: changed-collection-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: ansible_platform_collection/**

      - name: Fail if there are changed files
        if: steps.changed-collection-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-collection-files.outputs.all_changed_files }}
        run: |
          echo "The following collection files were attempted to be changed:"
          for file in ${ALL_CHANGED_FILES}; do
            echo $file
          done
          exit 1
