---
name: collection integration test
on:
  push:
  pull_request:

jobs:
  ci_standalone:
    name: collection integration test
    runs-on: ubuntu-latest
    env:
      HEADLESS: "yes"

    steps:
      - uses: actions/checkout@v3

      - name: Clear proxy.yml
        run: cp tools/configs/proxy-config-no-services.yml tools/configs/proxy-config-sample.yml

      - name: Build the image
        run: make docker-compose-build

      - name: Spin up the dev env
        run: |
          ansible-playbook -v tools/ansible/smoke-test.yml \
            -e repo_root=$(pwd) \
            -e gateway_vars=$(readlink -f container-startup.yml)

      - name: Perform integration tests
        run: make collection-test
