---
name: collection completeness test
on:
  push:
  pull_request:

jobs:
  completeness_test:
    name: collection completeness test
    runs-on: ubuntu-latest
    env:
      HEADLESS: "yes"
    steps:
      - uses: actions/checkout@v3

      - name: Start the dev environment
        run: COMPOSE_UP_OPTS='-d' make docker-compose

      - name: Install make
        run: sudo apt install make

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        run: pip3.11 install -r requirements/requirements_dev.txt ansible-core

      - name: Perform completeness tests
        run: make collection-test-completeness
