---
name: Linting
env:
  LC_ALL: "C.UTF-8" # prevent ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
  CI_IMAGE: quay.io/ansible/jewel-ci:${{ github.base_ref || github.ref_name }}
on:
  pull_request:
  merge_group:
  push:
jobs:
  common-tests:
    name: ${{ matrix.tests.name }}
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_IMAGE }}
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tests:
          - name: api-ruff-check
            command: check_ruff
          - name: api-ruff-format
            command: check_ruff_format
    steps:
      - uses: actions/checkout@v4

      - name: Run check ${{ matrix.tests.name }}
        run: make ${{ matrix.tests.command }}
