---
name: Smoke-test dev env
on:
  push:
    branches:
      - devel  # This prevents annoying failure emails from pushing to feature branches on forks
  pull_request:
jobs:
  smoke-test:
    name: smoke-test dev env
    runs-on: ubuntu-latest
    env:
      HEADLESS: "yes"
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_SHA }}

      - name: Upgrade ansible-core
        run: python3 -m pip install --upgrade ansible-core

      - name: Build the image
        run: make docker-compose-build

      - name: Try out the dev env
        run: |
          ansible-playbook -v tools/ansible/smoke-test.yml \
            -e repo_root=$(pwd) \
            -e gateway_vars=$(readlink -f container-startup.yml)
